### PR TITLE
Fix issue 1422 human client FSM transition order issues.

### LINKED ISSUE #1422: Human Client Access Violation Upon Fatal Error From Server
Was playing around with the save format, and made a save that the UI accepts, but which fails to load properly on the server. When the client receives an error message from the server about the fatal error, there is an access violation in the client, at least in Windows. The problem happens around here:

https://github.com/freeorion/freeorion/blob/master/client/human/HumanClientFSM.cpp#L550

The comment immediately above this code suggests the possible cause of the problem.

I'm not sure how the code within `Client().ResetToIntro();`, which itself posts some events and does some transitions to kill the sever and similar things, will interact with the explicit transition here, but at least the explicit transition probably needs to happen before the message box.

### PR DESCRIPTION
**Pull request by LGM-Doyle**
I think that this PR fixes #1422.

The problem is that moving `discard_event()` to after the transition within `ResetToIntro()` means that the discard event null transition occurs from a state that has already been exited.

The PR expands the comments clarifying the boost state machine behavior everywhere in the code. 

Hopefully this corrects, my previous unclear explanation of what was happening in this section of code.

### CODE REVIEW

File: client/human/HumanClientFSM.cpp [hunk 1]
```diff
@@ -114,9 +114,13 @@ boost::statechart::result WaitingForSPHostAck::react(const HostSPGame& msg) {
 
 boost::statechart::result WaitingForSPHostAck::react(const Disconnection& d) {
     if (TRACE_EXECUTION) DebugLogger() << "(HumanClientFSM) PlayingGame.Disconnection";
-    //Note: Any transit<> transition must occur before the MessageBox().
-    // MessageBox blocks and can allow other events to transit<> to a new state
-    // which makes this transit fatal.
+    // Note: All transitions, transit<> or disable_event(), must occur in the order
```
Comment (geoffthemedio) [inline client/human/HumanClientFSM.cpp]: disable or discard?

Comment (geoffthemedio) [reply client/human/HumanClientFSM.cpp]: "must occur in the order that they cause changes to state machine" is unclear.

File: client/human/HumanClientFSM.cpp [hunk 2]
```diff
@@ -114,9 +114,13 @@ boost::statechart::result WaitingForSPHostAck::react(const HostSPGame& msg) {
...
+    // that they cause changes to the state machine.
+    // - MessageBox blocks the UI, but continues handling events so other events
```
Comment (geoffthemedio) [inline client/human/HumanClientFSM.cpp]: MessageBox handles events? Or the FSM continues handling events while MessageBox has the UI blocked? Why does a UI block matter to the FSM?

File: client/human/HumanClientFSM.cpp (hunk 1 above)
Comment (geoffthemedio) [reply client/human/HumanClientFSM.cpp]: the phrase I quoted is still there and still doesn't make sense (or appears tautological)

File: client/human/HumanClientFSM.cpp (hunk 2 above)
Comment (geoffthemedio) [reply client/human/HumanClientFSM.cpp]: Then say the MessageBox starts handling events, rather than continues, since it wasn't handling any events before it blocked the UI.

**Comment by Vezzra** [comment]
Fixed the issue on OSX. No more in-game windows left over when returning to main menu.

File: client/human/HumanClientFSM.cpp (hunk 1 above)
Comment (LGM-Doyle) [reply client/human/HumanClientFSM.cpp]: I laughed when I read "appears tautological".

I expanded the comment so that it hopefully is clear why the incorrect code ordering crashes. 

The comment was long and repeated. I moved it to the top of the file, with doxygen notation to create a separate page and added references to it at all the locations in code where it was repeated.

File: client/human/HumanClientFSM.cpp (hunk 2 above)
Comment (LGM-Doyle) [reply client/human/HumanClientFSM.cpp]: clarified.

**Comment by geoffthemedio** [comment]
better now.

the top-of-file comment still isn't great / perfect, but I don't have any immediate specific complaints.

**Comment by LGM-Doyle** [comment]
I agree a non-local comment is less likely to be read when it needs to be read.

However, I felt that the comment having reached comically long proportions and being repeated 12 times risked being updated inconsistently in differing locations, resulting in one correct comment and 11 misleading comments. 

This way there is one correct comment, that no one will read :)

**Comment by geoffthemedio** [comment]
I meant the current comment, which is at the top of the file, isn't great. Not that it being at the top of the file isn't great. It's fine where it is, just not written perfectly.

**Comment by LGM-Doyle** [comment]
I'll need more specific criticism of the comment, if you want it changed.  I wrote it, so it seems clear to me.

I'm trying to summarize enough of the `boost::statechart` manual/tutorial so that the mechanics of reactions and the sequencing of state transitions are clear enough that the ordering requirements in the code are obvious.

**Comment by geoffthemedio** [comment]
As I wrote before, I don't have any immediate specific complaints. Just a vague feeling it could be improved. But it's fine as is.

Suppose I should merge this then...
