### PR TITLE
Fix drop down list doesn't track anchor on app resize.

### LINKED ISSUE #1139: Resizing Game Window While Droplist Open Doesn't Reposition Dropped List
Drop the focus or system droplist on the sidepanel, then resize the game window (with the droplist still open). The sidepanel repositions itself, but the dropped list doesn't.
drop reposition

### PR DESCRIPTION
**Pull request by LGM-Doyle**
The drop down list and its anchor are in different event pumps.  If the
entire app is resized the drop down list may not track the anchor.

This commit closes the drop down list if the app is resized.

This PR fixes #1139.

### CODE REVIEW

File: GG/src/DropDownList.cpp [hunk 1]
```diff
@@ -185,6 +192,13 @@ void ModalListPicker::EndRun() {
 bool ModalListPicker::Dropped() const
 { return m_dropped; }
 
+void ModalListPicker::Render()
+{
+    // If the app changes size while the drop down is open, then close it.
+    if (m_initial_appsize != Pt(GG::GUI::GetGUI()->AppWidth(), GG::GUI::GetGUI()->AppHeight()))
```
Comment (geoffthemedio) [inline GG/src/DropDownList.cpp]: Is this preferable to connecting HumanClientApp::WindowResizedSignal to EndRun ?

**Comment by LGM-Doyle** [comment]
No it was not preferable.  It is now fixed.

Thanks.

File: GG/src/DropDownList.cpp [hunk 2]
```diff
@@ -174,14 +183,23 @@ void ModalListPicker::ModalInit()
     m_dropped = true;
     m_lb_wnd->Hide(); // to enable CorrectListSize() to work
     CorrectListSize();
+    m_resized_connection = Connect(GG::GUI::GetGUI()->WindowResizedSignal,
+                                     boost::bind(&ModalListPicker::WindowResizedSlot, this, _1, _2));
```
Comment (geoffthemedio) [inline GG/src/DropDownList.cpp]: odd indenting

**Review by geoffthemedio — CHANGES_REQUESTED** [review]

**Review by geoffthemedio — APPROVED** [review]
