### PR TITLE
Fix meter rounding issues

### LINKED ISSUE #4190: Refuel Bug
Weekly test build version is 2022-08-30.000f16b. 21st Multi-player

Ship fails to move on turn it refuel to 1.0 fuel

https://www.freeorion.org/forum/viewtopic.php?f=28&t=12610

### PR DESCRIPTION
**Pull request by Grummel7**
This should fix #4190 and other potential rounding issues

### CODE REVIEW

File: universe/Meter.h [hunk 1]
```diff
@@ -48,7 +48,7 @@ class FO_COMMON_API Meter {
         init = FromFloat(DEFAULT_VALUE);
     }
 
-    constexpr void AddToCurrent(float adjustment) noexcept { cur = FromFloat(FromInt(cur) + adjustment); }
+    constexpr void AddToCurrent(float adjustment) noexcept { cur += FromFloat(adjustment); }
```
Comment (Grummel7) [inline universe/Meter.h:51]: While not being totally wrong, it does not make sense to use fixed point arithmetic for storage only, while all the calculations are one by casting to float and back.
