### PR TITLE
Use std::mutex instead of recursive one in Pending.h (hopefully works…

### LINKED ISSUE #3252: Crash to desktop when trying to launch FO on macOS
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.4.10+, build 81807c6a864d51fefdd8433d821609cbc4008da8
* **Operating System**: macOS 10.14.6
* **Fetched as** 
  * Compiled from source

Description
-----------

﻿﻿When I try to launch FO on macOS, the app immediately crashes. On the terminal I get this output:
```
Assertion failed: (e == 0), function ~recursive_mutex, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/libcxx/libcxx-400.9.4/src/mutex.cpp, line 64.
Abort trap: 6
```
freeorion.log: [freeorion.log.zip](https://github.com/freeorion/freeorion/files/5625216/freeorion.log.zip)

### PR DESCRIPTION
**Pull request by agrrr3**
… on MacOS)

maybe fixes #3252 

this version does not use recursive locking

also see #3253

### CODE REVIEW

**Comment by agrrr3** [comment]
@o01eg i implemented this without having the opportunity to see if the game still builds/and checksumming check works. if you have spare time I'd appreciate if you could check.

**Comment by Vezzra** [comment]
I tried this PR on Mac too to see if it fixes #3252, but I get build errors:
```
In file included from /Users/user/SoftwareProjekte/FO/main/src/universe/Encyclopedia.cpp:1:
In file included from /Users/user/SoftwareProjekte/FO/main/src/universe/Encyclopedia.h:10:
/Users/user/SoftwareProjekte/FO/main/src/universe/../util/Pending.h:90:16: error: no matching function for call to 'WaitForPendingUnlocked'
        return WaitForPendingUnlocked(std::move(pending), do_not_care_about_result);
               ^~~~~~~~~~~~~~~~~~~~~~
```
(The same error occurs several times.)

**Comment by agrrr3** [comment]
@Vezzra sorry, i should have send an update. this is also not building on linux. i have (two) versions locally which do build but which do not work on linux.

**Comment by Vezzra** [comment]
@agrrr3,

> sorry, i should have send an update. this is also not building on linux.

No problem. Just mark the PR as draft for now, and mark is as ready for review once you want me to test it.

**Comment by agrrr3** [comment]
@Vezzra could you test if the current revision gets you to the start screen on MacOS? (i dont really expect the game to work)

**Comment by Vezzra** [comment]
> could you test if the current revision gets you to the start screen on MacOS? (i dont really expect the game to work)

Yes, I can build FO now on Mac and get to the start screen. Launching a game however fails (as you expected) - Quickstart just ends up on a blank screen, audio playing, nothing more happens. Single Player crashes before even getting to the game setup dialog.

**Comment by agrrr3** [comment]
@Vezzra at home i made the game work, but i think it could be probably broken for switching default directory (because i guess that is the reason for the Pending.h to be so complicated). should we use that revision as a quickfix if it makes freeorion work on MacOS again?

**Comment by agrrr3** [comment]
ok, i checked and switching default directory also works, need to clean up the code

**Comment by agrrr3** [comment]
@Vezzra  can you run the game with this? Note I get AI errors, but also wth current master only.

**Comment by Vezzra** [comment]
This time, I get a tiny bit further: game starts and gets to very briefly (as in: a short flash) displaying the map screen, then crashes. Output on the terminal:
```
dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/Executables/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: lazy symbol binding failed: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

dyld: Symbol not found: __Z7Objectsv
  Referenced from: /Volumes/FreeOrion/FreeOrion.app/Contents/MacOS/../SharedSupport/libfreeorioncommon.dylib
  Expected in: flat namespace

Abort trap: 6
```
Logs: [logs.zip](https://github.com/freeorion/freeorion/files/5679553/logs.zip)

**Comment by agrrr3** [comment]
@Vezzra I am a bit confused what causes that dynamic symbol lookup (probably not this PR). I removed all unnecessary debugging code just in case. Can you try again?

**Comment by agrrr3** [comment]
@vezzra also what was the last time (which revision) you were able to run a game?

**Comment by agrrr3** [comment]
@geoffthemedio the error vezzra posted last looks like it could have something to do with 19becd6ac0da5adfb04590c298ddbed6b085180c

**Comment by geoffthemedio** [comment]
@agrrr3 Maybe https://github.com/freeorion/freeorion/tree/IncludeAppInterface will help...?

**Comment by agrrr3** [comment]
@vezzra i cherry-picked geoffs fix on top of my changes. could you try again, please?

(note i dont have the chance to build here, so i rely on the CI to see that the change works for linux)

**Comment by Vezzra** [comment]
@agrrr3, yep, now I can build and run FO, and successfully start a game (tried both Quickstart and Single Player).

Whatever you did, it fixed the problem.

👍 😃

**Comment by agrrr3** [comment]
@geoffthemedio i cherry-picked your commit from  https://github.com/freeorion/freeorion/tree/IncludeAppInterface  and now it works also on Mac, i put this on ready for review. If I should change anything just let me know.

File: util/Pending.h [hunk 1]
```diff
@@ -38,62 +38,84 @@ namespace Pending {
...
+    template <typename T>
+    boost::optional<T> WaitForPending(boost::optional<Pending<T>>& pending, bool do_not_care_about_result = false) {
+        if (!pending)
+            return boost::none;
+        std::lock_guard<std::mutex> lock(pending->m_mutex);
+        if (!pending || !(pending->pending)) {
+            return boost::none;
+        }
+        if (auto tt = WaitForPendingUnlocked(std::move(*pending), do_not_care_about_result)) {
+            pending = boost::none; // XXX
```
Comment (geoffthemedio) [inline util/Pending.h]: `XXX`?

File: util/Pending.h [hunk 2]
```diff
@@ -38,62 +38,84 @@ namespace Pending {
...
         if (pending) {
-            std::lock_guard<std::recursive_mutex> lock(pending->m_mutex);
-            if (auto tt = WaitForPending(pending))
+            std::lock_guard<std::mutex> lock(pending->m_mutex);
+            if (!pending) {
+                return stored;
+            }
+            if (auto tt = WaitForPendingUnlocked(std::move(*pending))) {
                 std::swap(*tt, stored);
+                // FIXME always setting to none is probably wrong
```
Comment (geoffthemedio) [inline util/Pending.h]: Is this FIXME important?

Comment (agrrr3) [reply util/Pending.h]: Before I did not have time for doing another thorough code analysis of the code paths of the old code (at b2f465fe65774a7012c234c53a4b3b84066b3a08) and i wanted to see first that it works for vezzra.

So, it looks for all non-exceptional cases that pending was always none for both SwapPending and WaitForPending, so this should be ok.

There is some throw for std::future_status::deferred state, but AFAIU that state should not happen.

File: util/Pending.h (hunk 1 above)
Comment (agrrr3) [reply util/Pending.h]: Setting pending to boost::none probably could happen in WaitForPendingUnlocked, instead of in the wrapping WaitForPending and SwapPending. Beforehand it was in WaitForPending and SwapPending was wrapping it. I guess it is mostly matter of style where to do that, what would you prefer?

**Comment by geoffthemedio** [comment]
If this works, then it's fine, I guess. It seems to work on Windows.

I don't understand the changes upon a quick look, or care to get deep into it, so if it fixes things on OSX and doesn't break Linux, then OK.
