### PR TITLE
Fix bug524 wait for ai crash

### LINKED ISSUE #524: Server keeps waiting for crashed AI on startup
So I was messing up an import in AI-scripts - AI could not be initialized:

```
2016-03-13 18:37:02.198722 [error] AI : AIClientApp.cpp:51 : AIClientApp::AIClientApp : Failed to initialize Python AI.  Exiting.
2016-03-13 18:37:02.198722 [error] AI : camain.cpp:61 : main() caught exception(std::runtime_error): AIClientApp::AIClientApp : Failed to initialize Python AI.  Exiting.
```

However, the server kept waiting:

```
2016-03-13 18:37:01.244667 [debug] Server : ai-path set to 'AI'
2016-03-13 18:37:01.244667 [debug] Server : ai-config not set.
2016-03-13 18:37:01.248668 [debug] Server : done starting C:\Users\FabianAdmin\FreeOrionDevelopment\FreeOrion\freeorionca.exe
2016-03-13 18:37:01.248668 [debug] Server : (ServerFSM) WaitingForSPGameJoiners.CheckStartConditions
2016-03-13 18:38:13.496800 [debug] Server : ServerNetworking::DisconnectImpl : disconnecting player 1
```

(Last Entry: Me shutting down FO)

Expected Result: Server shuts down if the AI can not be initialized and some error gets displayed.

### PR DESCRIPTION
**Pull request by LGM-Doyle**
I think this fixes #524 and #534. 

It produces the MessageBox saying "ERROR: Python AI for AI_1 crashed."  as request by @Morlic-fo when I used the python code provided by @Cjkjvfnby during initialization of the AI.

### CODE REVIEW

File: client/AI/AIClientApp.cpp [hunk 1]
```diff
@@ -77,6 +70,29 @@ const AIBase* AIClientApp::GetAI()
 { return m_AI; }
 
 void AIClientApp::Run() {
+
```
Comment (adrianbroher) [inline client/AI/AIClientApp.cpp]: Unnecessary whitespace.

File: server/ServerApp.cpp [hunk 2]
```diff
@@ -318,7 +318,6 @@ int ServerApp::GetNewDesignID()
 
 void ServerApp::Run() {
     DebugLogger() << "FreeOrion server waiting for network events";
-    std::cout << "FreeOrion server waiting for network events" << std::endl;
```
Comment (geoffthemedio) [inline server/ServerApp.cpp:321]: Why?

With this line, there is some indication of what's happening if the server process is run from command line.

File: server/ServerFSM.cpp [hunk 3]
```diff
@@ -1321,6 +1370,11 @@ sc::result WaitingForTurnEndIdle::react(const SaveGameRequest& msg) {
     return transit<WaitingForSaveData>();
 }
 
+sc::result WaitingForTurnEndIdle::react(const Error& msg) {
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: This appears to be overriding the containing state equivalent, but with nothing changed. Is it necessary?

File: client/AI/AIClientApp.cpp [hunk 4]
```diff
@@ -96,22 +112,21 @@ void AIClientApp::Run() {
...
-        } else {
-            boost::this_thread::sleep_for(boost::chrono::milliseconds(250));
-        }
+void AIClientApp::StartPythonAI() {
+    PythonAI* python_ai = new PythonAI();
+    if (!(python_ai->Initialize())) {
+        const std::string err_msg = "AIClientApp::AIClientApp : Failed to initialize Python AI.  Exiting Soon.";
+        ErrorLogger() << err_msg;
+        Networking().SendMessage(
+            ErrorMessage(str(FlexibleFormat(UserString("ERROR_PYTHON_AI_CRASHED")) % PlayerName()) , true));
```
Comment (geoffthemedio) [inline client/AI/AIClientApp.cpp:125]: The server presumably already knows the player name... Is this necessary?

If the text is going to be shown in the human client, I'd rather do the stringtable lookup in that process, rather than before sending the message to the server.

File: client/human/HumanClientFSM.cpp [hunk 5]
```diff
@@ -445,19 +469,23 @@ boost::statechart::result PlayingGame::react(const Error& msg) {
...
+
+    //Note: Any transit<> transition must occur before the MessageBox().
+    // MessageBox blocks and can allow other events to transit<> to a new state
+    // which makes this transit fatal.
+    boost::statechart::result retval = fatal ? transit<IntroMenu>() : discard_event();
     ClientUI::MessageBox(UserString(problem), true);
 
     if (fatal) {
-        Client().GetClientUI()->GetMessageWnd()->HandleGameStatusUpdate(UserString("RETURN_TO_INTRO") + "\n");
+        Client().EndGame(true);
```
Comment (geoffthemedio) [inline client/human/HumanClientFSM.cpp:482]: I renamed the AI script directory, then started freeorion, then quickstarted. I got a crash around here, though I'm now unable to reproduce it.

**Comment by geoffthemedio** [comment]
If a first game is run, then a second that has an AI crash, or a game gets far enough into init to have opened the messages / empires window, then the AI crashes, I sometimes get the windows left open when back on the intro screen...
windows_left_open

File: server/ServerApp.cpp (hunk 2 above)
Comment (LGM-Doyle) [inline server/ServerApp.cpp:321]: I didn't think of running the server process standalone.  I've restored the line.

File: server/ServerFSM.cpp (hunk 3 above)
Comment (LGM-Doyle) [inline server/ServerFSM.cpp]: HandleErrorMessage() doesn't return if the error is fatal.  I've added a comment to its definition.

File: client/AI/AIClientApp.cpp (hunk 4 above)
Comment (LGM-Doyle) [inline client/AI/AIClientApp.cpp:125]: At this point in the initialization, before the AI has tried to join the game the server's PlayerConnection is not initialized with the AI id or name.  It gets initialized when the AI joins.  I added a comment to clarify and left the code as is.

**Comment by LGM-Doyle** [comment]
I hid the messages and empire windows, which are owned by the client and not the MapWnd, during the transition.

File: server/ServerFSM.cpp (hunk 3 above)
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: How is that relevant to my question that it follows (regarding overriding functions seemingly unnecessarily)?

File: server/ServerApp.cpp (hunk 2 above)
Comment (geoffthemedio) [inline server/ServerApp.cpp:321]: It's useful for attaching the debugger to catch something before whatever state the server is in on the galaxy setup screen.

File: server/ServerFSM.cpp (hunk 3 above)
Comment (LGM-Doyle) [inline server/ServerFSM.cpp]: I misunderstood your question.

You were correct. The handlers for the inner states were redundant.  I have removed them and pushed the changes.  

I re-tested for the same cases we have already used, starting and re-starting the AI a few times.
