### PR TITLE
Remove buffer with uncompressed data on save

### LINKED ISSUE #5398: Out of memory error on saving game
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 0.5.1.1
* **Operating System**: Linux Ubuntu 24.04
* **Fetched as** 
  * Compiled from source

Description
-----------
After some players press turn button and send orders the server starts saving the game and got killed with out of memory error.

Last log lines are:

```
2026-01-11 13:26:45.530146 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:130 : SaveGame(zlib-xml) filename: /var/lib/freeorion/save/FO0030/FreeOrion_0186_20260111_132645.mps
2026-01-11 13:26:45.530192 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:133 : Compiling save empire and preview data
2026-01-11 13:26:45.530447 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:50 : CompileSaveGamePreviewData(...) player_save_game_data size: 7
2026-01-11 13:26:45.530667 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:205 : Allocating buffers for XML serialization...
2026-01-11 13:26:45.530671 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:208 : String Max Size: 9223372036854775807
2026-01-11 13:26:45.530673 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:210 : Reserving Capacity:: 536870900
2026-01-11 13:26:47.503919 {0x00007b8b578d8780} [debug] server : SerializeEmpire.cpp:375 : EmpireManager takes at least: 74934 kB
2026-01-11 13:26:49.338474 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:74 : Universe::serialize : Getting gamestate data
2026-01-11 13:26:49.347063 {0x00007b8b578d8780} [debug] server : Universe.cpp:3475 : GetEmpireKnownObjectsToSerialize encoding empire: -1
2026-01-11 13:26:49.563527 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:109 : Universe::serialize : serializing universe width: 1577.55
2026-01-11 13:26:49.566647 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:130 : Universe::serialized : serializing 285 ship designs
2026-01-11 13:26:49.862781 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:181 : Universe::serialize : serializing empire object visibility for 8, 8, 8, 8 empires
2026-01-11 13:26:49.969616 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:198 : Universe::serializing 8111 objects
2026-01-11 13:26:49.973230 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:202 : Universe::serialize : serializing 13307 destroyed object ids
2026-01-11 13:26:51.721700 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:211 : Universe::serialize : serializing empire known objects for 8 empires
2026-01-11 13:26:51.723131 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:218 : Universe::serialize : serializing id allocator version = 3
2026-01-11 13:26:51.723283 {0x00007b8b578d8780} [debug] IDallocator : IDAllocator.cpp:287 : Serialize IDAllocator()  server id = -1 empire id = -1
2026-01-11 13:26:51.724436 {0x00007b8b578d8780} [debug] IDallocator : IDAllocator.cpp:287 : Serialize IDAllocator()  server id = -1 empire id = -1
```

Expected Result
---------------
Players can turn without issues.

```
2026-01-11 13:02:17.297665 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:130 : SaveGame(zlib-xml) filename: /var/lib/freeorion/save/FO0030/FreeOrion_0186_20260111_130217.mps
2026-01-11 13:02:17.297667 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:133 : Compiling save empire and preview data
2026-01-11 13:02:17.297965 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:50 : CompileSaveGamePreviewData(...) player_save_game_data size: 7
2026-01-11 13:02:17.298843 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:205 : Allocating buffers for XML serialization...
2026-01-11 13:02:17.298880 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:208 : String Max Size: 9223372036854775807
2026-01-11 13:02:17.298884 {0x00007b8b578d8780} [debug] server : SaveLoad.cpp:210 : Reserving Capacity:: 536870900
2026-01-11 13:02:19.038704 {0x00007b8b578d8780} [debug] server : SerializeEmpire.cpp:375 : EmpireManager takes at least: 74934 kB
2026-01-11 13:02:20.308402 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:74 : Universe::serialize : Getting gamestate data
2026-01-11 13:02:20.312892 {0x00007b8b578d8780} [debug] server : Universe.cpp:3475 : GetEmpireKnownObjectsToSerialize encoding empire: -1
2026-01-11 13:02:20.477520 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:109 : Universe::serialize : serializing universe width: 1577.55
2026-01-11 13:02:20.479269 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:130 : Universe::serialized : serializing 285 ship designs
2026-01-11 13:02:20.777279 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:181 : Universe::serialize : serializing empire object visibility for 8, 8, 8, 8 empires
2026-01-11 13:02:20.863919 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:198 : Universe::serializing 8111 objects
2026-01-11 13:02:20.866090 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:202 : Universe::serialize : serializing 13307 destroyed object ids
2026-01-11 13:02:22.278791 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:211 : Universe::serialize : serializing empire known objects for 8 empires
2026-01-11 13:02:22.281175 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:218 : Universe::serialize : serializing id allocator version = 3
2026-01-11 13:02:22.281396 {0x00007b8b578d8780} [debug] IDallocator : IDAllocator.cpp:287 : Serialize IDAllocator()  server id = -1 empire id = -1
2026-01-11 13:02:22.282398 {0x00007b8b578d8780} [debug] IDallocator : IDAllocator.cpp:287 : Serialize IDAllocator()  server id = -1 empire id = -1
2026-01-11 13:02:22.308101 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:251 : Universe::serialize : serializing 22 types of statistic
2026-01-11 13:02:22.411131 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:276 : Universe serializing done. UniverseObjects take at least: 4840 kB and empire known objects at least: 61252 kB
2026-01-11 13:02:22.498412 {0x00007b8b578d8780} [debug] server : SerializeUniverse.cpp:279 : Universe other stuff takes at least: 11375 kB
```

Steps to reproduce
------------------

* Load save before crash 

[freeorion-save-log-oom-issue.zip](https://github.com/user-attachments/files/24552514/freeorion-save-log-oom-issue.zip)

* Login as BlueAward or ThinkSome.
* Press turn button.
* Somehow it could be reproduces only on the server.

### PR DESCRIPTION
**Pull request by o01eg**
Should fix #5398 

Actually saves made with this PR are broken. I'll try to compare saves if it have something missing.

### CODE REVIEW

**Comment by o01eg** [comment]
What I can see `compressed_str` is cut compared to `compressed_str` before the PR.

**Comment by o01eg** [comment]
Looks like it's required to call destructor of the steam for it to be fully flushed.

**Comment by geoffthemedio** [comment]
I guess you'd need to decompress via stream, not into a buffer, when loading / deserializing a save as well? Otherwise it would also require a large buffer, which you now have no way to determine the required size of before decompressing...

**Comment by geoffthemedio** [comment]
> Looks like it's required to call destructor of the steam for it to be fully flushed.

Just calling .flush() doesn't do it reliably?

File: server/SaveLoad.cpp [hunk 1]
```diff
@@ -201,64 +201,52 @@ int SaveGame(const std::string& filename, const ServerSaveGameData& server_save_
...
-                    // compression-filter gamestate into compressed string
-                    boost::iostreams::filtering_ostreambuf o;
-                    o.push(boost::iostreams::zlib_compressor());
-                    o.push(boost::iostreams::base64_encoder());
-                    o.push(c_sink);
-                    boost::iostreams::copy(s_source, o);
-                    c_sink.flush();
 
-                    save_preview_data.uncompressed_text_size = serial_str.size();
+                    save_preview_data.uncompressed_text_size = compressed_str.size();
```
Comment (geoffthemedio) [inline server/SaveLoad.cpp]: seems problematic if this is used for a deserialization uncompressed buffer...

**Comment by o01eg** [comment]
> I guess you'd need to decompress via stream, not into a buffer, when loading / deserializing a save as well? Otherwise it would also require a large buffer, which you now have no way to determine the required size of before decompressing...

`LoadGame` reads the universe from `compressed_str`.

File: server/SaveLoad.cpp (hunk 1 above)
Comment (o01eg) [reply server/SaveLoad.cpp]: `uncompressed_text_size` is unused so there no issue, but we can use `basic_counter` filter to count uncompressed data.

**Comment by o01eg** [comment]
> > 
> 
> Just calling .flush() doesn't do it reliably?

I haven't found it in documentation but it looks like so.
