### PR TITLE
fix misplaced color buffer usage in PlanetPanel

### LINKED ISSUE #5522: Detection circles visibility on map depends on toggling unrelated elements
Bug Report
==========
Environment
-----------

* **FreeOrion Version**: master / a few recent weekly builds (does not happen on release 5.1)
* **Operating System**: Windows 11
* **Graphic card used**: integrated Intel
* **Fetched as** 
  * Weekly development build
  * Compiled from source

Description
-----------
Whether detection circles are visible or not on galaxy map should only depend on the appropriate setting "Detection range circles".

Meanwhile, with "Detection range circles" on:
- with "Galaxy map gas rendering" off and "Galaxy map star fields rendering" on -> detection circles vanish just like the background gas clouds
- with "Galaxy map gas rendering" off and "Galaxy map star fields rendering" off -> detection circles show up again as both background gas and background stars are not rendered

for the record,
- with "Galaxy map gas rendering" on and "Galaxy map star fields rendering" off -> detection circles are visible
- with both "Galaxy map gas rendering" on and "Galaxy map star fields rendering" on -> detection circles are also visible

Steps to reproduce
------------------
Start new game with your homeworld selected, brought in view somewhere to the side so it is not hidden under options menu, and then tweaking the options in the menu and seeing the various results per above. Could be done with right click menu options too, if that menu is enabled.

The concern is that disabling "Galaxy map gas rendering" appears to visually disable "detection range circles" too, unless star fields are disabled, too.

Bug Hunt
==========
`MapWnd::Render()` has this order of rendering:

`    RenderStarfields();`
`    RenderGalaxyGas();`
`    RenderVisibilityRadii();`

It would seem something about rendering star fields breaks detection circles (visibility radii) but rendering galaxy gas can fix it.

BUT git bisect points at 97f91dbd8a3c625411cfec3e3c5de89489f33bcf as the changelist that surfaces the defect

The change promotes vertices buffer for `SidePanel::PlanetPanel` from local variable in `Render()` to member variable (although it's tripled in size, always reconstructed, and without server buffer creation)

And it also changes `glColor` calls with `glDisableClientState(GL_COLOR_ARRAY);` into calls with color buffer accompanying the vertex buffer, with `glEnableClientState(GL_COLOR_ARRAY);` 

Not really sure what would be the benefit of doing the latter part about colors, but that's where problem lies, with the color buffer usage. Reverting that part back to `glColor` fixes the issue. Although moving buffer activation to after all those gl client state calls also fixes the stuff.

Hazy on this but looks like activating the buffers too early before pushing client state etc puts the GL rendering state in some.. dangling pointer situation? Over stale buffer or something? And maybe rendering galaxy gas or some other things can fix it, depending on what that rendering does with GL state? Who knows. There are places in the codebase I saw that do not do the whole client state push/pop, and also some places would do `glPushAttrib` like GL_ENABLE_BIT flags and then pop that state, but not all the places. So it seems quite delicate balance there

I have a proposed improvement/fix to go back to `glColor` usage alongside making vertex buffer lean again and a bit more useful (not recomputed). Although as mentioned, moving vertex activation between the gl client state push/pop also fixes the stuff

### PR DESCRIPTION
**Pull request by Blue-Award**
this fixes https://github.com/freeorion/freeorion/issues/5522

### CODE REVIEW

**Comment by Blue-Award** [comment]
I went a step back on https://github.com/freeorion/freeorion/commit/97f91dbd8a3c625411cfec3e3c5de89489f33bcf here to make the vertices buffer smaller, and not use color buffer at all, but kept the main move of vertex buffer into member variable/persistent storage, and improved on it not to recompute on every render call (and make it server buffer)

I'm storing original rectangle for which the vertices were originally computed and recompute if that changes. Was trying to plug m_verts.clear() here and  there like SizeMove() but that would only trigger on resize, not on normal moves, and I found it difficult to find where to plug in in order to mark this worthwhile to recompute. The stack doesn't really require prerender on no size change, so I think the child control never gets ordered to recompute things - but it does so on things like actually changing size.

figured storing the original rectangle works for any reason the panel would change (size or location) without needing to hook up somewhere to the signal stack

**Comment by Blue-Award** [comment]
as mentioned in bug report, what would also fix the issue would be moving color buffer activation within bounds of gl client state push/pop before doing the draw. I am just really not sure what's the benefit of the color array if it actually does longer stretches of same color painting, not something more complicated.

File: UI/SidePanel.cpp [hunk 1]
```diff
@@ -2586,12 +2580,13 @@ void SidePanel::PlanetPanel::Render() {
     const GG::Clr title_background_colour = ClientUI::WndOuterBorderColor();
     const GG::Clr border_colour = (m_selected ? m_empire_colour : ClientUI::WndOuterBorderColor());
 
+    if (m_verts_rect.UpperLeft() != ul || m_verts_rect.LowerRight() != lr) {
```
Comment (geoffthemedio) [inline UI/SidePanel.cpp]: rather than storing the Rect, could you put the code to clear / refill m_verts into PlanetPanel::PreRender? That should get called before Render any time a prerender is flagged as required. The currently includes whenever, in PlanetPanel:: SizeMove, the new size differs from the old, but could also be for any SizeMove call.

**Comment by geoffthemedio** [comment]
> I am just really not sure what's the benefit of the color array if it actually does longer stretches of same color painting, not something more complicated.

In general I want to move towards more use of buffers, including for colours, rather than the older API calls like glColorXX. glColor(GG::Clr clr) unpacks the clr into its uint8_t components and calls glColor4ub, which is one of the oldest parts of the immediate fixed function GL pipeline.

File: UI/SidePanel.cpp (hunk 1 above)
Comment (Blue-Award) [reply UI/SidePanel.cpp]: This is something I mentioned, I tried dirtying the render state by always clearing m_verts in PlanetPanel::SizeMove (so only these vertices are dirtied, not child controls like planet specials etc) but from what I saw it was never called on normal move, only on actual resize. It's like something else higher up would cause PlanetPanel::SizeMove in some cascade but if and only if that higher level stuff gets resized not just moved around

I wanted to hook to SidePanel::SizeMove to coerce it into causing its PlanetPanels to redraw always, not only on resize, but it was quite confusing, even some compiler optimizations would make debugging harder by jumping around to code from unrelated controls, and I sort of gave up, and idea to store relevant rectangle wasn't even that original as I saw it somewhere in comment as a "todo" to do exactly that ( can't recall which control that was)

I will have a second look but please believe me it wasn't as easy as it sounds, while storing Rect is doing exactly what I wanted, not more, not less, and only when required indeed, not trying to track who calls what where and why to avoid unintentional redraws. Someone clearly wanted not to do a lot of layout recalc on normal moves without resizing so wanted to avoid that too, but if I didn't recalculate those vertices, then background/title etc would stay behind while other elements like planet, meters etc would still move around

Maybe it would be an option not to recreate those vertices when there was no resize, and instead of basing the values from ur/lr, make them from "zero point" and then apply some translation matrix to move the vertexes per current ur/lr? I guess that would be more computation on GL side but maybe not that bad considering it's presumably GPU time vs CPU time

**Comment by Blue-Award** [comment]
> > I am just really not sure what's the benefit of the color array if it actually does longer stretches of same color painting, not something more complicated.
> 
> In general I want to move towards more use of buffers, including for colours, rather than the older API calls like glColorXX. glColor(GG::Clr clr) unpacks the clr into its uint8_t components and calls glColor4ub, which is one of the oldest parts of the immediate fixed function GL pipeline.

Well, moving the color buffer activation to after the gl client state push and the like, also fixes this, was wondering why to do that if that kinda triples the buffer size and adds second one, but I'm happy to gather that working on color buffer is more modern approach even if that's still GL function calls not some shader stuff, and hope it goes well with whatever OpenGl is doing with GPU. Whatever you were doing on master it does feel like it paid off because I do feel things are working  smoother. 

I'll revert to color buffer usage just move it into a place that fixes the issue

File: UI/SidePanel.cpp (hunk 1 above)
Comment (Blue-Award) [reply UI/SidePanel.cpp]: Think what might work is redoing vertices only in DoLayout, but relative to Pt0, and in render doing glTranslateF. This should be a benefit when we have server buffer for vertices that is not recreated in every frame, not needed to recreate on move without resize, and with resize, it would get recreated by DoLayout

Although color array when brought back needs additional care because color switches for example on selection change. Redoing colors in every Render sounds sus, what if it introduces unwanted CPU/GPU syncs or something 

I think I will descope this PR  to just fix the defect and let buffer improvement on the side

Comment (geoffthemedio) [reply UI/SidePanel.cpp]: Possibly since the PlanetPanels are two levels nested into containing controls (SidePanel, PlanetPanelContainer), they might not be actually moved relative to their container / parent control when that parent control is moved, and thus don't have SizeMove called.

But you could probably call their RequirePrerender functions from within SidePanel or PlanetPanelContainer SizeMove...

**Comment by Blue-Award** [comment]
I've reduced this to just the fix for https://github.com/freeorion/freeorion/issues/5522 (keeping vertex sand color buffers  unchanged, just moving their activation)

I'll give a second shot at caching those PlanetPanel buffers on a separate PR

File: UI/SidePanel.cpp (hunk 1 above)
Comment (Blue-Award) [reply UI/SidePanel.cpp]: Requiring Prerender seems to cause too much recomputation cause entire panel layout would be racalced I believe - there is a reason why this part is skipped when size does not change. Though probably not such a big deal, that Of course could expose more targeted function to just redo the vertices/color buffers and call that rather than requirePrerender

anyway I descoped this PR to just the fix and will have another go at not recalcing vertices in separate PR

**Comment by geoffthemedio** [comment]
Could you look over the rendering code for other cases where the order of buffer activation and client state activation looks wrong in a similar way to this...? I'm confused / surprised it causes problems so it might happen elsewhere...

**Comment by Blue-Award** [comment]
Hazy on this but I think activation of these buffers does something to client state and then if you push the client state AFTER and pop it later, it goes back to having that buffer still active rather than not active? Some drawing pointer referencing that buffer? And that can mess with some subsequent renderings depending on what they do or don't do?

I was making a pass indeed and haven't seen something like that elsewhere, I saw buffer activations between client state push/pop in other places, generally right before first glDrawArrays, after client state push (like in the fix here)

 I did see instances of client state not being pushed/popped at all, although most places do that. Maybe it would be worthwhile to have client state guarded by scoped helper so deconstructor does the popping? RAII style. And either way do that more consistently in various Render calls

and also seemed it could be better to do gl enable bits push/pop but barely any places do that. Most places push/pop client state bits but not wider gl bits. Some places do push enable bits and pop them, most assume to turn something on then off or vice versa, not heeding what actually was the previous/original gl state. But by far not an expert here so dunno

**Comment by geoffthemedio** [comment]
> Hazy on this but I think activation of these buffers does something to client state

The color buffer activate function is at most:
````
        glBindBuffer(GL_ARRAY_BUFFER, b_name);
        glColorPointer(4, GL_UNSIGNED_BYTE, 0, nullptr);
        glBindBuffer(GL_ARRAY_BUFFER, 0);
````

with the`glBindBuffer` calls sometimes omitted, and vertex buffers using instead glVertexPointer.

I see a mix of activating buffers before and after enabling client states in other code. eg. `Rectangle` in DrawUtil.cpp activates its vertex buffer before the client state enable, whereas `XMark` does it after.

And ChatGPT says the order of 1. enabling/disabling client state and 2. the glBindBuffer & glColorPointer calls shouldn't matter as they are independent bits of state, the setting of which can be freely reordered.

We can do this reordering if it fixes rendering for you, I guess due to buggy drivers? But I'd rename the issue as it doesn't appear to actually be a bug as written now...

**Comment by Blue-Award** [comment]
> > Hazy on this but I think activation of these buffers does something to client state
> 
> The color buffer activate function is at most:
> 
> ```
>         glBindBuffer(GL_ARRAY_BUFFER, b_name);
>         glColorPointer(4, GL_UNSIGNED_BYTE, 0, nullptr);
>         glBindBuffer(GL_ARRAY_BUFFER, 0);
> ```
> 
> with the`glBindBuffer` calls sometimes omitted, and vertex buffers using instead glVertexPointer.
> 
> I see a mix of activating buffers before and after enabling client states in other code. eg. `Rectangle` in DrawUtil.cpp activates its vertex buffer before the client state enable, whereas `XMark` does it after.
> 
> And ChatGPT says the order of 1. enabling/disabling client state and 2. the glBindBuffer & glColorPointer calls shouldn't matter as they are independent bits of state, the setting of which can be freely reordered.
> 
> We can do this reordering if it fixes rendering for you, I guess due to buggy drivers? But I'd rename the issue as it doesn't appear to actually be a bug as written now...

 it's not about order of activating various client states, it's about doing something BEFORE pushing client state and popping client state after being done restores the state before push which includes the buffers activation 

Again hazy on this, as I am not sure what glPushClientAttrib stores exactly but it has e.g. GL_CLIENT_VERTEX_ARRAY_BIT so it surely stores stuff about the arrays, and when I ask LLM about it it says that glPushClientAttrib does store stuff which those activate calls do

I have not seen any other place in code that would activate buffers BEFORE doing glPushClientAttrib

Enter Render with state X -> activate buffers and enter state Y -> store state (Y) -> mess with state to draw things and you're in state Z -> pop client state and you're in state Y -> leave render with state Y that includes buffer activation stuff instead of state X that you entered with

With changes, enter with state X -> store state (X) -> activate buffers and do other stuff to draw Y+Z > pop client state and you're in state X -> leaving render eith client state the same as it was entered

**Comment by Blue-Award** [comment]
Granted the situation is weird, I think it makes sense that pushing client state remembers something about color pointer and whatnot, but this still may be driver dependent what happens if/when things go out whack

**Comment by Blue-Award** [comment]
Would be nice if someone else on different GPU/system confirmed if that is an issue for them though maybe even if it is an issue, might show in some other manner elsewhere

**Comment by Blue-Award** [comment]
Ah just saw you mentioned you don't replicate it

**Comment by Blue-Award** [comment]
LLM has cited this for me:
https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glColorPointer.xml

> When a color array is specified, size, type, stride, and pointer are saved as client-side state, in addition to the current vertex array buffer object binding.

> Color array parameters are client-side state and are therefore not saved or restored by [glPushAttrib](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glPushAttrib.xml) and [glPopAttrib](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glPopAttrib.xml). Use [glPushClientAttrib](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glPushClientAttrib.xml) and [glPopClientAttrib](https://registry.khronos.org/OpenGL-Refpages/gl2.1/xhtml/glPopClientAttrib.xml) instead.



`GLRGBAColorBuffer::activate()` is doing `glColorPointer` stuff indeed, and `glPushClientAttrib` is storing that stuff, apparently, and it therefore doesn't sound good to do it before `glPushClientAttrib` but rather after hence that's the state we want to preserve, from before doing anything to client state

Like everything points to me this is a bug that on my particular system realizes as not showing detection circles in certain circumstances but it's very possible it does other stuff or even maybe nothing on other systems

**Comment by Blue-Award** [comment]
In shortest words this is about `activate` happening before `glPushClientAttrib` rather than after, and that's what this PR fixes

**Comment by geoffthemedio** [comment]
> I think it makes sense that pushing client state remembers something about color pointer and whatnot

After more ChatGPT questioning, it seems to agree that color pointers are part of the affected client state.

> I have not seen any other place in code that would activate buffers BEFORE doing glPushClientAttrib

I mentioned one above: `Rectangle`: https://github.com/freeorion/freeorion/blob/master/GG/src/DrawUtil.cpp#L194-L198

**Comment by Blue-Award** [comment]
> > I think it makes sense that pushing client state remembers something about color pointer and whatnot
> 
> After more ChatGPT questioning, it seems to agree that color pointers are part of the affected client state.
> 
> > I have not seen any other place in code that would activate buffers BEFORE doing glPushClientAttrib
> 
> I mentioned one above: `Rectangle`: https://github.com/freeorion/freeorion/blob/master/GG/src/DrawUtil.cpp#L194-L198

Ah hmm maybe I was only looking through freeorion gui code, not GiGi, or only concerned about color buffers as that was what seemed to be the issue.  Was some time ago, before I opened the issue even
