### PR TITLE
Fix some issues with empire color from save game

### LINKED ISSUE #2339: Infinite lobby changes after loading game
### Environment
* **FreeOrion Version**: https://github.com/o01eg/freeorion/commit/8abe0395641043d9a79bdf9c711f467e9a18f329 based on 0.4.8
* **Operating System**: Ubuntu Linux x64 18.04.1
* **Fetched as** 
  * Compiled from source

### Description
After trying to load saved game clients and server starts to infinite ping-pong of Lobby Update messages:

```
01:12:14.880570 [debug] server : ServerApp.cpp:971 : ServerApp::UpdateSavePreviews: Sending 5 previews in response.
01:12:20.397811 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 2857
01:12:20.398285 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:12:20.398311 [debug] FSM : ServerFSM.cpp:104 : PlayerSetupData:
01:12:20.398335 [debug] FSM : ServerFSM.cpp:119 :  ... 1 : xxcc, PLAYER, RANDOM
01:12:20.398345 [debug] FSM : ServerFSM.cpp:119 :  ... 2 : JonCST, PLAYER, RANDOM
01:12:20.398428 [debug] server : SaveLoad.cpp:544 : LoadEmpireSaveGameData: filename: /var/lib/freeorion/save/./AsJoPrXx523/FreeOrion_0006_20181220_020119.mps path:"/var/lib/freeorion/save/./AsJoPrXx523/FreeOrion_0006_20181220_020119.mps"
01:12:20.400527 [debug] timer : ScopedTimer.cpp:34 : LoadEmpireSaveGameData: /var/lib/freeorion/save/./AsJoPrXx523/FreeOrion_0006_20181220_020119.mps time:     2088 µs
01:12:20.400624 [debug] FSM : ServerFSM.cpp:1457 : New save file: true. PSD changed: false. Important changes: false
01:12:20.535772 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 1 of type Lobby Update and size 5196
01:12:20.536155 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:12:20.536176 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:12:20.571052 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:12:20.571461 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:12:20.571483 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:12:20.634294 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 1 of type Lobby Update and size 5196
01:12:20.634695 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:12:20.634723 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:12:20.698369 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 1 of type Lobby Update and size 5196
01:12:20.698745 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:12:20.698768 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:12:20.701535 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:12:20.701928 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
...
01:13:27.816459 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:13:27.835270 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:13:27.835626 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:13:27.835699 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:13:27.836394 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 1 of type Lobby Update and size 5196
01:13:27.836699 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:13:27.836717 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:13:27.854568 [trace] network : ServerNetworking.cpp:736 : ServerNetworking::DisconnectImpl : disconnecting player 1 this = 0x55f208642e70
01:13:27.854683 [debug] FSM : ServerFSM.cpp:737 : MPLobby::react(Disconnection) player id: 1
01:13:27.854695 [debug] FSM : ServerFSM.cpp:738 : Remaining player ids: 
01:13:27.854703 [debug] FSM : ServerFSM.cpp:742 :  ... 2 (JonCST)
01:13:34.858059 [debug] server : Process.cpp:275 : Process::Impl::Kill calling kill(m_process_id, SIGKILL)
01:13:34.858148 [debug] server : Process.cpp:277 : Process::Impl::Kill calling waitpid(m_process_id, &status, 0)
01:13:34.858169 [debug] server : Process.cpp:279 : Process::Impl::Kill done
01:13:34.858674 [trace] network : ServerNetworking.cpp:74 : PlayerConnection destruction player id 1 this = 0x55f208642e70
01:13:34.858713 [trace] network : ServerNetworking.cpp:89 : Player connection already down.
01:13:34.858782 [trace] network : ServerNetworking.cpp:726 : ServerNetworking::AcceptConnection : connected to new player
01:13:34.858814 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:13:34.859331 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:13:34.859381 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: true
01:13:34.859732 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: -1 of type Join Game and size 388
01:13:34.859759 [debug] server : Message.cpp:908 : ExtractJoinGameMessageData() from  client type 32625
01:13:34.859872 [debug] server : ServerFSM.cpp:901 : MPLobby.JoinGame Try to login player xxcc with cookie: 2616a93c-74fb-463b-bcfc-24f5198cce04
01:13:34.859888 [debug] FSM : ServerFSM.cpp:960 : (ServerFSM) MPLobby.JoinGame player accepted: xxcc
01:13:34.859915 [debug] server : ServerFSM.cpp:385 : ServerFSM.EstablishPlayer Assign new player id 3
01:13:34.859925 [trace] network : ServerNetworking.cpp:157 : PlayerConnection(@ 0x55f208f04ee0)::EstablishPlayer(3, xxcc, 1, v0.4.8 [build 2018-08-23.26f16b0] MSVC 2015)
01:13:34.859934 [debug] server : ServerFSM.cpp:397 : ServerFSM.EstablishPlayer player xxcc get cookie: 2616a93c-74fb-463b-bcfc-24f5198cce04
01:13:34.885130 [debug] server : Building.cpp:407 : BuildingTypeManager checksum: 8384120
01:13:34.885427 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 8702640
01:13:34.885661 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 4039802
01:13:34.885882 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 6891042
01:13:34.886761 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 5425412
01:13:34.887602 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 4596210
01:13:34.887717 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 7001025
01:13:34.910135 [debug] server : ShipDesign.cpp:766 : HullTypeManager checksum: 337389
01:13:34.917759 [debug] server : ShipDesign.cpp:265 : PartTypeManager checksum: 7136787
01:13:34.919021 [debug] server : ShipDesign.cpp:1540 : PredefinedShipDesignManager checksum: 877965
01:13:35.030598 [debug] server : Species.cpp:629 : SpeciesManager checksum: 6661376
01:13:35.041101 [debug] server : Tech.cpp:715 : TechManager checksum: 1204321
01:13:42.208782 [debug] server : Process.cpp:275 : Process::Impl::Kill calling kill(m_process_id, SIGKILL)
01:13:42.208879 [debug] server : Process.cpp:277 : Process::Impl::Kill calling waitpid(m_process_id, &status, 0)
01:13:42.208901 [debug] server : Process.cpp:279 : Process::Impl::Kill done
01:13:42.209022 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:13:42.209522 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:13:42.209550 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:13:42.210113 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:13:42.210470 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
01:13:42.210487 [debug] FSM : ServerFSM.cpp:1457 : New save file: false. PSD changed: true. Important changes: false
01:13:42.211017 [trace] network : ServerNetworking.cpp:303 : Server received message from player id: 2 of type Lobby Update and size 5196
01:13:42.211408 [debug] FSM : ServerFSM.cpp:1037 : Get message from host or allowed player.
...
```

### Expected Result
Server and clients successfully sync lobby state.

### Steps to reproduce
Not sure what leads to this but it doesn't happened every time someone loads game.

### LINKED ISSUE #2349: Multiplayer lobby freezes on matching empire colors of unknown player and AI
### Environment
* **FreeOrion Version**: https://github.com/freeorion/freeorion/commit/4ee5f067f96a88caeb412a7c4a025a139003a71c
* **Operating System**: Gentoo Linux AMD64
* **Graphic card used**: GeForce GTX 750 Ti/PCIe/SSE2
* **Fetched as** 
  * Compiled from source

### Description

When loading multiplayer game it possible to freeze lobby on duplicated colors:

color_on_load

### Expected Result
Additional unknown players should reset empire color to other unused ones.

### Steps to reproduce
* Create multiplayer game with some players.
* Save the game and stop the server.
* Start multiplayer lobby in "new game" state.
* Connect player who isn't from saved game.
* Set him color of AI's empire.
* Load the saved game.
* Lobby freezes.

### PR DESCRIPTION
**Pull request by o01eg**
Prevents collision when previous players have same color as players from
save game.
Adds collision diagnostic.

Fixes #2349 and fixes #2339 introduced in https://github.com/freeorion/freeorion/pull/2248

### CODE REVIEW

File: server/ServerFSM.cpp [hunk 1]
```diff
@@ -565,6 +572,16 @@ namespace {
                 }
             }
 
+            if (!colour_is_new) {
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: This block conditionally sets `colour_is_new` to false so probably you don't want the `!` here?

File: server/ServerFSM.cpp [hunk 2]
```diff
@@ -969,6 +986,8 @@ sc::result MPLobby::react(const LobbyUpdate& msg) {
     // if got important lobby changes so players shoul reset their ready status
     bool has_important_changes = false;
 
+    const GG::Clr CLR_NONE = GG::Clr(0, 0, 0, 0);
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: I think there's already `GG::CLR_ZERO` defined for this...

Comment (o01eg) [reply server/ServerFSM.cpp]: It requires to link to GG library.

Comment (geoffthemedio) [reply server/ServerFSM.cpp]: If you know how to initialize the constants in the header, sounds good. I just get errors that the expression must have a constant value. Not sure why my attempts don't.

Comment (o01eg) [reply server/ServerFSM.cpp]: Pushed new commit with changes `GG::Clr` to have a constexpr constructor and used it in `ClrConstants.h`. If it will build without error I'll remove all other color constants from `ClrConstants.cpp`.

Comment (o01eg) [reply server/ServerFSM.cpp]: I suppose `ClrConstants.cpp` should be removed from Xcode project as well.

**Comment by o01eg** [comment]
It looks like #2339 is the same as #2349 but as viewed from server (I applied  #2248 over 0.4.8).

**Comment by geoffthemedio** [comment]
Seems OK.

File: server/ServerFSM.cpp (hunk 2 above)
Comment (Vezzra) [reply server/ServerFSM.cpp]: The manually maintained Xcode project has been removed quite a while ago, so no need for that.
