### PR TITLE
Fix bug#1556 server terminates on non unique parses

### LINKED ISSUE #1556: Server not terminated when client throws from duplicate FOCS name
### Environment
* **FreeOrion Version**: 0.4.7+
* **Operating System**: Linux
* **Fetched as** Compiled from source

### Description
When client crashes from a duplicate FOCS definition name, server is left running.
Possibly first reported in https://github.com/freeorion/freeorion/issues/1504#issuecomment-299726646

### Expected Result
All processes terminate.

### Steps to reproduce
* Copy some FOCS definition to a new file
 (`default/scripting/ship_designs/SD_CARRIER.focs.txt`->`default/scripting/ship_designs/SD_CARRIERX.focs.txt`)
* Start client and new game
* Client throws `what():  ERROR: More than one predefined ship design has the name SD_CARRIER`
* `freeoriond` and all `freeorionca` processes are left running

### PR DESCRIPTION
**Pull request by LGM-Doyle**
This PR fixes #1556.

***Problem Description***

The problem has several contributing factors.
- the parser code indicates some errors with the `boost::spirit error` handling and emits `ErrorLogger()` messages and throws `std::runtime_error` for uniqueness errors.
- The universe <X>TypeManagers are singletons created as static local function variables.  
- The <X>TypeManagers parse in their constructors.  Any exceptions in the constructor cause the construction to fail and the constructor to be run on every access of the manager.  Consequently, exceptions are thrown on the server, in the UI, in the python code and other difficult to catch locations.  

***This Solution***
This PR transforms the non-uniqueness exceptions into a failure condition on the parse of the name of the type in question.  These errors are now handled with the regular `boost::spirit` error handler.

### CODE REVIEW

File: parse/BuildingsParser.cpp [hunk 1]
```diff
@@ -48,21 +40,23 @@ namespace {
...
             qi::_r1_type _r1;
             qi::eps_type eps;
 
             const parse::lexer& tok = parse::lexer::instance();
 
             building_type
                 =   tok.BuildingType_
-                >   parse::detail::label(Name_token)                > tok.string        [ _a = _1 ]
+                >   parse::detail::label(Name_token)
+                >   tok.string        [ _pass = is_unique_(_r1, "BuildingType", _1), _a = _1 ]
```
Comment (geoffthemedio) [inline parse/BuildingsParser.cpp]: what does this do?

File: parse/ParseImpl.h [hunk 2]
```diff
@@ -13,6 +13,31 @@
...
+        }
+    };
+
+    /// A functor to insert a \p value with key \p key into \p map.
+    struct insert {
+        typedef void result_type;
+
+        template <typename Map, typename Value>
+        result_type operator() (Map& map, const std::string& key, Value* value) const {
+            map.insert(std::make_pair(key, value));
```
Comment (geoffthemedio) [inline parse/ParseImpl.h]: prefer {} on same line

File: universe/ShipDesign.cpp [hunk 3]
```diff
@@ -1075,17 +1075,17 @@ PredefinedShipDesignManager::PredefinedShipDesignManager() {
         throw;
     }
 
-    if (GetOptionsDB().Get<bool>("verbose-logging")) {
+    if (true || GetOptionsDB().Get<bool>("verbose-logging")) {
```
Comment (Dilvish-fo) [inline universe/ShipDesign.cpp]: was this meant to be a temporary change during testing?

File: universe/ShipDesign.cpp [hunk 4]
```diff
@@ -1075,17 +1075,17 @@ PredefinedShipDesignManager::PredefinedShipDesignManager() {
...
-        DebugLogger() << "Monster Ship Designs:";
-        for (const std::map<std::string, ShipDesign*>::value_type& entry : m_monster_designs) {
-            const ShipDesign* d = entry.second;
-            DebugLogger() << " ... " << d->Name();
-        }
+        // DebugLogger() << "Monster Ship Designs:";
+        // for (const std::map<std::string, ShipDesign*>::value_type& entry : m_monster_designs) {
+        //     const ShipDesign* d = entry.second;
+        //     DebugLogger() << " ... " << d->Name();
+        // }
```
Comment (Dilvish-fo) [inline universe/ShipDesign.cpp]: likewise, was this meant to be a temporary change during testing?

File: parse/ParseImpl.h (hunk 2 above)
Comment (LGM-Doyle) [reply parse/ParseImpl.h]: Fixed.

File: universe/ShipDesign.cpp (hunk 3 above)
Comment (LGM-Doyle) [reply universe/ShipDesign.cpp]: Thanks for the catching this.

File: universe/ShipDesign.cpp (hunk 4 above)
Comment (LGM-Doyle) [reply universe/ShipDesign.cpp]: And this.

File: parse/BuildingsParser.cpp (hunk 1 above)
Comment (LGM-Doyle) [reply parse/BuildingsParser.cpp]: The `_pass_type` parameter is the third parameter to the `boost::spirit` semantic actions.  Setting it to false causes the parse to fail at that point.

This line calls `is_unique_()` to check if the name is already in the map of existing building types.  If the name is not unique, that will set `_pass` false and cause the parse to fail and the error message generated by `boost::spirit` will point at the name token to indicate where the parse failed.

**Review by LGM-Doyle — COMMENTED** [review]
Changes are done.

File: parse/BuildingsParser.cpp (hunk 1 above)
Comment (dbenage-cx) [reply parse/BuildingsParser.cpp]: Fails with boost 1.64 (and likely 1.63) without `-DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION`: 
```tty
[ 23%] Linking CXX shared library libfreeorioncommon.so
In file included from /opt/projects/boost/1_64_0/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator.hpp:12:0,
                 from /opt/projects/boost/1_64_0/include/boost/phoenix/function/detail/cpp03/function_operator.hpp:6,
                 from /opt/projects/boost/1_64_0/include/boost/phoenix/function/function.hpp:58,
                 from /opt/projects/boost/1_64_0/include/boost/phoenix/function.hpp:11,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/include/phoenix_function.hpp:11,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/support/terminal.hpp:18,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/support/common_terminals.hpp:15,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex/lexer/terminals.hpp:13,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex/lexer.hpp:13,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex.hpp:13,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex/lexer_lexertl.hpp:15,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/include/lex_lexertl.hpp:16,
                 from /opt/projects/freeorion/parse/Lexer.h:6,
                 from /opt/projects/freeorion/parse/ReportParseError.h:4,
                 from /opt/projects/freeorion/parse/ParseImpl.h:4,
                 from /opt/projects/freeorion/parse/BuildingsParser.cpp:3:
/opt/projects/boost/1_64_0/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator_10.hpp: In instantiation of ‘const typename boost::phoenix::detail::expression::function_eval<F, A0, A1, A2>::type boost::phoenix::function<F>::operator()(const A0&, const A1&, const A2&) const [with A0 = boost::phoenix::actor<boost::spirit::attribute<1> >; A1 = char [13]; A2 = boost::phoenix::actor<boost::spirit::argument<0> >; F = parse::detail::is_unique; typename boost::phoenix::detail::expression::function_eval<F, A0, A1, A2>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::detail::tag::function_eval, boost::proto::argsns_::list4<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<parse::detail::is_unique>, 0l>, boost::phoenix::actor<boost::spirit::attribute<1> >, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l>, boost::phoenix::actor<boost::spirit::argument<0> > >, 4l> >]’:
/opt/projects/freeorion/parse/BuildingsParser.cpp:52:83:   required from here
/opt/projects/boost/1_64_0/include/boost/phoenix/function/detail/cpp03/preprocessed/function_operator_10.hpp:57:76: error: invalid conversion from ‘const char*’ to ‘param_type {aka char*}’ [-fpermissive]
             return detail::expression::function_eval<F, A0 , A1 , A2>::make(f, a0 , a1 , a2);
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In file included from /opt/projects/boost/1_64_0/include/boost/phoenix/core/argument.hpp:14:0,
                 from /opt/projects/boost/1_64_0/include/boost/phoenix/core.hpp:15,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/include/phoenix_core.hpp:11,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/support/terminal.hpp:17,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/support/common_terminals.hpp:15,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex/lexer/terminals.hpp:13,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex/lexer.hpp:13,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex.hpp:13,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/home/lex/lexer_lexertl.hpp:15,
                 from /opt/projects/boost/1_64_0/include/boost/spirit/include/lex_lexertl.hpp:16,
                 from /opt/projects/freeorion/parse/Lexer.h:6,
                 from /opt/projects/freeorion/parse/ReportParseError.h:4,
                 from /opt/projects/freeorion/parse/ParseImpl.h:4,
                 from /opt/projects/freeorion/parse/BuildingsParser.cpp:3:
/opt/projects/boost/1_64_0/include/boost/phoenix/core/expression.hpp:63:21: note:   initializing argument 3 of ‘static boost::phoenix::expr_ext<Actor, Tag, A>::type boost::phoenix::expr_ext<Actor, Tag, A>::make(typename boost::call_traits<A>::param_type ...) [with Actor = boost::phoenix::actor; Tag = boost::phoenix::detail::tag::function_eval; A = {parse::detail::is_unique, boost::phoenix::actor<boost::spirit::attribute<1> >, char*, boost::phoenix::actor<boost::spirit::argument<0> >}; boost::phoenix::expr_ext<Actor, Tag, A>::type = boost::phoenix::actor<boost::proto::exprns_::basic_expr<boost::phoenix::detail::tag::function_eval, boost::proto::argsns_::list4<boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<parse::detail::is_unique>, 0l>, boost::phoenix::actor<boost::spirit::attribute<1> >, boost::proto::exprns_::basic_expr<boost::proto::tagns_::tag::terminal, boost::proto::argsns_::term<char*>, 0l>, boost::phoenix::actor<boost::spirit::argument<0> > >, 4l> >]’
         static type make(typename call_traits<A>::param_type... a)
                     ^~~~
CMakeFiles/freeorionparseobj.dir/build.make:86: recipe for target 'CMakeFiles/freeorionparseobj.dir/parse/BuildingsParser.cpp.o' failed
```

Related previous workaround in #1271 (not that this is the only solution)

Comment (LGM-Doyle) [reply parse/BuildingsParser.cpp]: Thanks for finding and reporting this.  

It appears to be losing the constness of the string literal while trying to convert it to `const std::string`.  I've changed the parameter of `is_unique` to `const char* const`, which hopefully prevents it from trying to convert anything.

I also switched all of the literals to token, which they should have been in the first place.

**Comment by dbenage-cx** [comment]
TY for working on this, working well here with a console message and server log error instead of crashing:  (copying SD_CARRIER to SD_CARRIERx)
```tty
/opt/projects/freeorion/default/scripting/ship_designs/SD_CARRIERx.focs.txt:2:11: Parse error.  Expected string here:
ShipDesign
    name = "SD_CARRIER"
           ^
...
```

```log
14:49:24.283379 [error] server : ParseImpl.h:26 : More than one ShipDesign has the same name, SD_CARRIER.
14:49:24.283584 [error] server : ReportParseError.cpp:95 : /opt/projects/freeorion/default/scripting/ship_designs/SD_CARRIERx.focs.txt:2:11: Parse error.  Expected string here:
ShipDesign
    name = "SD_CARRIER"
           ^
...
```

**Comment by geoffthemedio** [comment]
I think the "expected X here" message needs adjusting if dupes are going to be considered "not an X".

**Comment by LGM-Doyle** [comment]
A few things.

The line just above "expected string here" message "More than one ShipDesign has the same name, SD_CARRIER"  explains the problem in greater detail.  

Perhaps we should move the uniqueness checking out of the parser and into the calling code.  Each individual file has parsed correctly.  The uniqueness check is either stating that the whole directory did not parse correctly, or that game logic/mechanics constraints require a unique building name.  Interpreted the second way, this is an error/check that should be done in the game logic.

Even though the parsing error message is not perfect, this does fix the crashes which cause hung processes, which is arguably important enough to fix and leave the parse error message as future work.

Also, I tried and failed to fix the error message.

**Comment by geoffthemedio** [comment]
> Perhaps we should move the uniqueness checking out of the parser and into the calling code.
> ...
>this does fix the crashes which cause hung processes, which is arguably important enough

sounds reasonable

**Comment by LGM-Doyle** [comment]
Do you mean, 
a) sounds reasonable this fixes a crash merge it as is, or
b) sounds reasonable the uniqueness checks should be done in the caller, start refactoring?

**Comment by geoffthemedio** [comment]
(a) and (b + "if so inclined, as a separate pull request")
