### PR TITLE
Use empire ID instead of incorrect player ID for diplomacy

### LINKED ISSUE #2633: diplomatic message indicator not appearing (longturn server)
On the longturn server, send a peace or alliance proposal to a player your empire is at war with. The player receiving the offer should see the diplo status indicator in the empires window, but it doesn*t appear.

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #2633 missing diplomacy messages and flashing.

### CODE REVIEW

File: UI/PlayerListWnd.cpp [hunk 1]
```diff
@@ -320,7 +320,7 @@ namespace {
                 ErrorLogger() << "PlayerDataPanel::Render couldn't get client app!";
                 return;
             }
-            if (m_player_id != app->PlayerID()) {
+            if (m_empire_id != app->EmpireID()) {
```
Comment (geoffthemedio) [inline UI/PlayerListWnd.cpp:323]: Is the player ID actually incorrect here?

File: UI/PlayerListWnd.cpp [hunk 2]
```diff
@@ -333,7 +333,7 @@ namespace {
 
             // render incoming diplomatic message icon, if there is one
             const DiplomaticMessage& incoming_message_to_client =
-                Empires().GetDiplomaticMessage(m_player_id, app->PlayerID());
+                Empires().GetDiplomaticMessage(m_empire_id, app->EmpireID());
```
Comment (geoffthemedio) [inline UI/PlayerListWnd.cpp:336]: ... or just here?

File: UI/PlayerListWnd.cpp (hunk 1 above)
Comment (o01eg) [reply UI/PlayerListWnd.cpp:323]: I suppose it doesn't change anything as I tested with observers and moderators. Maybe better also test for `ALL_EMPIRES`.
