### PR TITLE
Do not send private information about empires

### LINKED ISSUE #2324: Encyclopedia shouldn't automatically disclose private information about empire's research
### Environment

* **FreeOrion Version**: 0.4.8, master

### Description
Encyclopedia provides information about researched techs, available parts, hulls, buildings. Enemy could use this to match his strategy.

https://a.doko.moe/ymgjnn.png

### Expected Result
Enemies shouldn't known researched capabilities of empires.

### Steps to reproduce
* Start game.
* Make some turns enough to research several techs. 
* Open `Pedia` -> `[Game - Empires]` -> Any other empire.
* Issue occurs.

### PR DESCRIPTION
**Pull request by o01eg**
One of the solutions fixes https://github.com/freeorion/freeorion/issues/2324

Sends empty data instead actual production and research queue if enabled. Sends only subset of techs known by both receiving and serializing empires.
Same implementation I use in my server.

### CODE REVIEW

**Comment by Dilvish-fo** [comment]
> Sends empty data instead actual production and research queue if enabled

Looking at the code, it seems to restrict things more than that-- it appears to also withhold info about what has actually been researched.  Does that lead to a lot of  the red 'Unknown' effects being listed in tooltips for enemy ship/planet meters?

File: util/SerializeEmpire.cpp [hunk 1]
```diff
@@ -98,8 +100,13 @@ template void ProductionQueue::serialize<freeorion_xml_iarchive>(freeorion_xml_i
 template <class Archive>
 void Empire::serialize(Archive& ar, const unsigned int version)
 {
-    ar  & BOOST_SERIALIZATION_NVP(m_id)
-        & BOOST_SERIALIZATION_NVP(m_name)
+    ar  & BOOST_SERIALIZATION_NVP(m_id);
+
+    bool visible = GetUniverse().AllObjectsVisible() ||
```
[the remark this answers is not in the document]
Comment (o01eg) [reply util/SerializeEmpire.cpp]: It should have correct `m_id` known when deciding about visibility so start of the function is a incorrect place. I'll place it after first `ar & ...` block.

[the remark this answers is not in the document]
Comment (o01eg) [reply util/SerializeEmpire.cpp]: Fixed.

**Comment by o01eg** [comment]
> Does that lead to a lot of the red 'Unknown' effects being listed in tooltips for enemy ship/planet meters?

Yes, there are. I'll try to send only techs known by both receiving and serializing empires.

**Comment by o01eg** [comment]
Rebased.

**Comment by o01eg** [comment]
Looks like something broken in MacOS travis.

**Comment by o01eg** [comment]
Rebased over fixed tests.

**Comment by geoffthemedio** [comment]
It seems like this would make more sense as a rule than an option. It would also be preferable to have the option being enabled mean to do something, not to not do something.

**Comment by o01eg** [comment]
Rebased. Made it rule instead of option.

File: util/SerializeEmpire.cpp [hunk 2]
```diff
@@ -107,31 +109,60 @@ void Empire::serialize(Archive& ar, const unsigned int version)
...
     if (Archive::is_loading::value && version < 1) {
         // adapt set to map
         std::set<std::string> temp_stringset;
         ar  & boost::serialization::make_nvp("m_techs", temp_stringset);
         m_techs.clear();
         for (auto& entry : temp_stringset)
             m_techs[entry] = BEFORE_FIRST_TURN;
+    } else if (Archive::is_saving::value && !visible && !GetGameRules().Get<bool>("RULE_SHOW_DETAILED_EMPIRES_DATA")) {
+        std::map<std::string, int> dummy_string_int_map;
+        // show only known tech without disclosure turn
```
Comment (geoffthemedio) [inline util/SerializeEmpire.cpp]: could you elaborate (in the comment) on what this bit is doing and why?

File: util/SerializeEmpire.cpp [hunk 3]
```diff
@@ -107,31 +109,60 @@ void Empire::serialize(Archive& ar, const unsigned int version)
...
-        & BOOST_SERIALIZATION_NVP(m_research_queue)
-        & BOOST_SERIALIZATION_NVP(m_research_progress)
-        & BOOST_SERIALIZATION_NVP(m_production_queue)
-        & BOOST_SERIALIZATION_NVP(m_available_building_types)
-        & BOOST_SERIALIZATION_NVP(m_available_part_types)
-        & BOOST_SERIALIZATION_NVP(m_available_hull_types)
-        & BOOST_SERIALIZATION_NVP(m_supply_system_ranges)
+    ar  & BOOST_SERIALIZATION_NVP(m_meters);
+    if (Archive::is_saving::value && !visible && !GetGameRules().Get<bool>("RULE_SHOW_DETAILED_EMPIRES_DATA")) {
+        ResearchQueue empty_research_queue(m_id);
```
Comment (geoffthemedio) [inline util/SerializeEmpire.cpp:145]: also comment what this is doing / why?

File: util/SerializeEmpire.cpp [hunk 4]
```diff
@@ -107,31 +109,60 @@ void Empire::serialize(Archive& ar, const unsigned int version)
...
+    }
+
+    ar  & BOOST_SERIALIZATION_NVP(m_supply_system_ranges)
         & BOOST_SERIALIZATION_NVP(m_supply_unobstructed_systems)
         & BOOST_SERIALIZATION_NVP(m_preserved_system_exit_lanes);
 
-    if (GetUniverse().AllObjectsVisible() ||
-        GetUniverse().EncodingEmpire() == ALL_EMPIRES ||
-        m_id == GetUniverse().EncodingEmpire())
+    if (visible)
```
Comment (geoffthemedio) [inline util/SerializeEmpire.cpp]: `{` to same line as `if`

File: util/SerializeEmpire.cpp [hunk 5]
```diff
@@ -107,31 +109,60 @@ void Empire::serialize(Archive& ar, const unsigned int version)
...
+        ProductionQueue empty_production_queue(m_id);
+        std::set<std::string> empty_string_set;
+        ar  & boost::serialization::make_nvp("m_research_queue", empty_research_queue)
+            & boost::serialization::make_nvp("m_research_progress", empty_research_progress)
+            & boost::serialization::make_nvp("m_production_queue", empty_production_queue)
+            & boost::serialization::make_nvp("m_available_building_types", empty_string_set)
+            & boost::serialization::make_nvp("m_available_part_types", empty_string_set)
+            & boost::serialization::make_nvp("m_available_hull_types", empty_string_set);
+    } else {
+        ar  & BOOST_SERIALIZATION_NVP(m_research_queue)
```
Comment (geoffthemedio) [inline util/SerializeEmpire.cpp:159]: comment for this block would also be helpful
