### PR TITLE
Fix segfault when trying to delete in empty password

### LINKED ISSUE #2658: Segfault when editing the server password entry field
```
(gdb) bt
#0  0x00007f1912bd2591 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007f1912f0679b in std::char_traits<char>::move (__n=<optimized out>, __s2=<optimized out>, __s1=<optimized out>) at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/char_traits.h:357
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_move (__n=<optimized out>, __s=<optimized out>, __d=<optimized out>)
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.h:360
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase (this=0x55ac72984930, __pos=<optimized out>, __n=1)
    at /var/tmp/portage/sys-devel/gcc-9.2.0-r2/work/build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:340
#4  0x000055ac6f211c65 in CensoredCUIEdit::ClearSelected() ()
#5  0x000055ac6f212736 in CensoredCUIEdit::KeyPress(GG::Key, unsigned int, GG::Flags<GG::ModKey>) ()
#6  0x00007f191359ee9e in GG::Wnd::HandleEvent(GG::WndEvent const&) () from /home/l29ah/projects/freeorion/build/libGiGi.so
#7  0x00007f19134feea9 in GG::GUIImpl::HandleKeyPress(GG::Key, unsigned int, GG::Flags<GG::ModKey>, int) () from /home/l29ah/projects/freeorion/build/libGiGi.so
#8  0x00007f1913e6d561 in GG::SDLGUI::HandleSystemEvents() () from /home/l29ah/projects/freeorion/build/libGiGiSDL.so
#9  0x000055ac6f10fa50 in HumanClientApp::HandleSystemEvents() ()
#10 0x00007f19134ca649 in GG::ModalEventPump::operator()() () from /home/l29ah/projects/freeorion/build/libGiGi.so
#11 0x00007f1913e6a73b in GG::SDLGUI::Run() () from /home/l29ah/projects/freeorion/build/libGiGiSDL.so
#12 0x000055ac6f0ebfb8 in mainSetupAndRun() ()
#13 0x000055ac6f0e3df1 in main ()
```

### Environment

* **FreeOrion Version**: 58f0b8eb0a6738b714db1dea0a402d7c77c5ac99
* **Operating System**:
* **Graphic card used**:
* **Fetched as** 
  * Compiled from source

### Steps to reproduce
Connect to @o01eg server and press `Delete` in the empty password input box.

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #2658.

Check for `end()` iterator in range as standard requires range to by valid: http://www.cplusplus.com/reference/string/string/erase/

### CODE REVIEW

File: UI/CUIControls.cpp [hunk 1]
```diff
@@ -1109,7 +1109,7 @@ void CensoredCUIEdit::ClearSelected() {
     auto it = m_raw_text.begin() + Value(low);
     auto end_it = m_raw_text.begin() + Value(high);
 
-    if (it == end_it)
+    if (it == m_raw_text.end() || it == end_it)
```
Comment (geoffthemedio) [inline UI/CUIControls.cpp:1112]: probably worth keeping regardless of my pull request for the same issue
