### PR TITLE
Fix reading game rules values from options

### LINKED ISSUE #3573: Parsed game rules couldn't be set from options
Bug Report
==========

Environment
-----------

* **FreeOrion Version**: 2021-10-05.980fd8e
* **Operating System**: Ubuntu Linux 20.04
* **Fetched as** 
  * Compiled from source

Description
-----------

After https://github.com/freeorion/freeorion/commit/9a0240fc04fb87d719f6c9bbce2203aff19963c3 game rules values from options got ignored

Expected Result
---------------

Games reads game rules values from options.

Steps to reproduce
------------------

* Start the game with `--setup.rules.RULE_ENABLE_SUPER_TESTER 0` options.
* Check rules in encyclopedia.

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #3573

### CODE REVIEW

File: util/GameRules.cpp [hunk 1]
```diff
@@ -146,9 +146,10 @@ namespace {
             rule.validator = std::make_unique<Validator<T>>();
         auto option_name = "setup.rules." + rule.name;
         if (!GetOptionsDB().OptionExists(option_name))
-            GetOptionsDB().Add<T>(std::move(option_name), rule.description,
+            GetOptionsDB().Add<T>(option_name, rule.description,
                                   boost::any_cast<T>(rule.default_value),
                                   rule.validator->Clone());
+        rule.value = GetOptionsDB().Get<T>(option_name);
```
Comment (geoffthemedio) [inline util/GameRules.cpp:153]: Does this always need to be set, or just if there was already an existing option for that option name? If the latter, would be clearer to put it in an `else` case...

Comment (geoffthemedio) [reply util/GameRules.cpp:153]: also should add a comment above this function that indicates that it may modify the passed-in `rule` by changing the value if an option already exists for that rule's value.

Comment (o01eg) [reply util/GameRules.cpp:153]: @geoffthemedio It should be set because even if options was already registered its value could be different.

Comment (o01eg) [reply util/GameRules.cpp:153]: Added comment about modification.

Comment (geoffthemedio) [reply util/GameRules.cpp:153]: My point was that if there was no option yet registered, then is there any need to set the rule value from the newly-registered option?

Comment (o01eg) [reply util/GameRules.cpp:153]: Yes, because options from XML not registered yet but already have value and marked with `recognized = false`. To access have still required to call `Add` method.
