### PR TITLE
Fix telepathic detection

### LINKED ISSUE #1618: Combat not always initiated between planets and aggressive fleets
### Environment

* **FreeOrion Version**:  Compiled from #1587  
* **Operating System**: Linux
  * Compiled from source

### Description
I've thought this was occasionally happening for a bit but hadn't found an example that was clear. Screenshot shows the problem, the previous turn two Yellow ships arrived and died, the next turn this ship arrived, debug data dump says it's on aggressive, but no combat or bombard is reported. That ship should be dead, but isn't. However, my system is still blockaded.

Autosaves for the previous turn and this, to see this happen it should be OK to simply hit end turn, can't guarantee combat won't happen.

### Expected Result
Combat should occur if there's an aggressive ship in system owned by a player other than planet owners.
[combat-failure.zip](https://github.com/freeorion/freeorion/files/1109671/combat-failure.zip)
[no-planet-combat.zip](https://github.com/freeorion/freeorion/files/1109670/no-planet-combat.zip)
screenshot_20170628_183720

### PR DESCRIPTION
**Pull request by Dilvish-fo**
This follows on the discussion in #1708 and on our forums, it fixes #1618 

The first commit causes m_empire_object_visibility to be serialized with the universe to prevent
visibility-effect-related errors/discrepancies upon savefile loading as was noted in #1618.  Since this changes serialization and breaks savefile compatibility, the examples from #1618 won't work, but the following two files are made with this and demonstrate the fix, with the desired result being that both files will have the same combat/no-combat status on turn T(17).  With just the first commit from this PR the result is no combat.
[T_minus_1.sav.zip](https://github.com/freeorion/freeorion/files/1267713/T_minus_1.sav.zip)
[T_minus_2.sav.zip](https://github.com/freeorion/freeorion/files/1267714/T_minus_2.sav.zip)

The second commit adjusts the backend processing of effects from SetVisibility so that they act as only a boon, never decreasing visibility.  This is compatible with all current uses in the scripts, and fixes #1618.  

As noted in the discussions, there is another more involved change being contemplated, which would change the parsing of SetVisibility to allow ValueRefs including min/max, and then the datatype for m_empire_object_visibility would be also planned to change.  In that event the second commit here should be reverted, but the material from the first commit would only need a small adjustment to datatype.  So even though this PR might be considered to be an interim fix, I think it is worthwhile.

### CODE REVIEW

**Comment by geoffthemedio** [comment]
looks fine

File: universe/Universe.cpp [hunk 1]
```diff
@@ -1659,7 +1659,11 @@ void Universe::ApplyEffectDerivedVisibilities() {
         for (const auto& object_entry : empire_entry.second) {
             if (object_entry.first <= INVALID_OBJECT_ID)
                 continue;
-            m_empire_object_visibility[empire_entry.first][object_entry.first] = object_entry.second;
+            // TODO: If/when the parser for SetVisibility is expanded to allow ValueRefs like
+            // max(Target.visibility, Basic)
+            // then the folllowing should be reverted to a simple assignment.
+            m_empire_object_visibility[empire_entry.first][object_entry.first] = 
+                std::max(object_entry.second, m_empire_object_visibility[empire_entry.first][object_entry.first]);
```
Comment (LGM-Doyle) [inline universe/Universe.cpp:1666]: As mentioned in #1708, I think that `SetMinVisibility()` and `SetMaxVisibility()` are clearer and more functional, (although not as functional as something evaluated like a ValueReef).  With this change setting visibility from an effect can only act as a set minimum visibility.

I don't object to merging this PR, which is a step forward and fixes the bug.
