### PR TITLE
Use structure instead of lambda in asynchronous socket close

### LINKED ISSUE #3062: Stack corruption on asynchronous socket close
Bug Report
==========

Environment
-----------
* **FreeOrion Version**: https://github.com/o01eg/freeorion/commit/43e576121442e27fde4514198d4a26c8f3029aa4 based on e352120
* **Operating System**: Ubuntu Linux 18.04
* **Fetched as** 
  * Compiled from source

Description
-----------
Suddenly got crash in asynchronous closure introduced in https://github.com/freeorion/freeorion/pull/2989

```
Core was generated by `/usr/lib/freeorion/freeoriond --setup.game.uid FO0010 --network.server.turn-tim'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f63af3db700 (LWP 13705))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f640b881801 in __GI_abort () at abort.c:79
#2  0x00007f640c274957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f640c27aae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f640c27ab21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f640c27ad54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f640d311494 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_log.so.1.65.1
#7  0x00007f640d309a2e in boost::log::v2_mt_posix::system_error::throw_(char const*, unsigned long, char const*, int) () from /usr/lib/x86_64-linux-gnu/libboost_log.so.1.65.1
#8  0x00007f640d328452 in boost::log::v2_mt_posix::aux::thread_specific_base::set_content(void*) const () from /usr/lib/x86_64-linux-gnu/libboost_log.so.1.65.1
#9  0x00007f640d300c7b in boost::log::v2_mt_posix::sources::aux::get_severity_level() () from /usr/lib/x86_64-linux-gnu/libboost_log.so.1.65.1
#10 0x000055575417cc9c in boost::log::v2_mt_posix::sources::aux::severity_level<LogLevel>::set_value (this=0x55575681ced8, level=LogLevel::trace) at /usr/include/boost/log/sources/severity_feature.hpp:135
#11 boost::log::v2_mt_posix::sources::basic_severity_logger<boost::log::v2_mt_posix::sources::basic_channel_logger<boost::log::v2_mt_posix::sources::basic_logger<char, boost::log::v2_mt_posix::sources::severity_channel_logger_mt<LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::log::v2_mt_posix::sources::multi_thread_model<boost::log::v2_mt_posix::aux::light_rw_mutex> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, LogLevel>::open_record_unlocked<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> > (args=..., this=0x55575681ce78)
    at /usr/include/boost/log/sources/severity_feature.hpp:252
#12 boost::log::v2_mt_posix::sources::basic_composite_logger<char, boost::log::v2_mt_posix::sources::severity_channel_logger_mt<LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::log::v2_mt_posix::sources::multi_thread_model<boost::log::v2_mt_posix::aux::light_rw_mutex>, boost::log::v2_mt_posix::sources::features<boost::log::v2_mt_posix::sources::severity<LogLevel>, boost::log::v2_mt_posix::sources::channel<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::open_record<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> > (args=..., this=<optimized out>)
    at /usr/include/boost/log/sources/basic_logger.hpp:459
#13 (anonymous namespace)::AutoresolveInfo::ReportInvisibleObjects (this=<optimized out>, this=<optimized out>) at ./combat/CombatSystem.cpp:1269
#14 boost::log::v2_mt_posix::record boost::log::v2_mt_posix::sources::basic_composite_logger<char, boost::log::v2_mt_posix::sources::severity_channel_logger_mt<LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::log::v2_mt_posix::sources::multi_thread_model<boost::log::v2_mt_posix::aux::light_rw_mutex>, boost::log::v2_mt_posix::sources::features<boost::log::v2_mt_posix::sources::severity<LogLevel>, boost::log::v2_mt_posix::sources::channel<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::open_record<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> >(boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> const&) () at ./combat/CombatSystem.cpp:1842
#15 0x000055575432e89b in PlayerConnection::<lambda()>::operator() (__closure=0x7f63ecaa9968) at ./server/ServerNetworking.cpp:197
#16 std::__invoke_impl<void, PlayerConnection::~PlayerConnection()::<lambda()> > (__f=...) at /usr/include/c++/7/bits/invoke.h:60
#17 std::__invoke<PlayerConnection::~PlayerConnection()::<lambda()> > (__fn=...) at /usr/include/c++/7/bits/invoke.h:95
#18 std::thread::_Invoker<std::tuple<PlayerConnection::~PlayerConnection()::<lambda()> > >::_M_invoke<0> (this=0x7f63ecaa9968) at /usr/include/c++/7/thread:234
#19 std::thread::_Invoker<std::tuple<PlayerConnection::~PlayerConnection()::<lambda()> > >::operator() (this=0x7f63ecaa9968) at /usr/include/c++/7/thread:243
#20 std::thread::_State_impl<std::thread::_Invoker<std::tuple<PlayerConnection::~PlayerConnection()::<lambda()> > > >::_M_run(void) (this=0x7f63ecaa9960) at /usr/include/c++/7/thread:186
#21 0x00007f640c2a56df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#22 0x00007f640c7b66db in start_thread (arg=0x7f63af3db700) at pthread_create.c:463
#23 0x00007f640b96288f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) f 15
#15 0x000055575432e89b in PlayerConnection::<lambda()>::operator() (__closure=0x7f63ecaa9968) at ./server/ServerNetworking.cpp:197
197	        TraceLogger(network) << "Socket closed for player id " << id;
(gdb) f 14
#14 boost::log::v2_mt_posix::record boost::log::v2_mt_posix::sources::basic_composite_logger<char, boost::log::v2_mt_posix::sources::severity_channel_logger_mt<LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::log::v2_mt_posix::sources::multi_thread_model<boost::log::v2_mt_posix::aux::light_rw_mutex>, boost::log::v2_mt_posix::sources::features<boost::log::v2_mt_posix::sources::severity<LogLevel>, boost::log::v2_mt_posix::sources::channel<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::open_record<boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> >(boost::parameter::aux::tagged_argument<boost::log::v2_mt_posix::keywords::tag::severity, LogLevel const> const&) () at ./combat/CombatSystem.cpp:1842
1842	            combat_state.ReportInvisibleObjects()));
(gdb) p combat_state
$3 = {valid_attacker_object_ids = std::set with 23 elements<error reading variable: Cannot access memory at address 0x574ef394810c593>, 
  empire_infos = std::map with 140067687178496 elements<error reading variable: Cannot access memory at address 0x50>, combat_info = @0x7f63af3dad20, next_fighter_id = 0, 
  destroyed_object_ids = std::set with 140067687178496 elements<error reading variable: Cannot access memory at address 0x50>}
```

Expected Result
---------------
Socket closed without crashing the server.

Steps to reproduce
------------------
Internet hiccups lead to freezes on socket closing are rare and hard to reproduce.

### PR DESCRIPTION
**Pull request by o01eg**
Supposed to prevent capture of unneeded data and memory corruption.

Should fix https://github.com/freeorion/freeorion/issues/3062

### CODE REVIEW

**Comment by geoffthemedio** [comment]
Why does or would this make any difference?

**Comment by o01eg** [comment]
I suppose lambda somehow captures deleted `this` pointer so I explicitly declare structure with required fields.

**Comment by adrianbroher** [comment]
Lamdas with captures are structs in a different dress.  I agree with @geoffthemedio, this code is functionally equivalent.  Also the backtrace shows that the issue is caused by the logger statement, so there is probably a concurrent write going on.

**Comment by o01eg** [comment]
@adrianbroher Isn't logger thread-safe?

**Comment by adrianbroher** [comment]
> @adrianbroher Isn't logger thread-safe?

¯\_(ツ)_/¯ seems like in this invocation it is not, but I'm also just guessing here.  Did you try instead to capture the `network` logger instance into the lambda?

**Comment by geoffthemedio** [comment]
Maybe put a single logger call in the constructor instead of in `operator()`, or in the calling code before the `std::thread` call?

> capture the `network` logger instance

Is that possible? Calls like `TraceLogger(network)` are a macro that expends, seemingly, into a for loop, not a getter for a reference to something, I think...
TraceLogger(network)

**Comment by o01eg** [comment]
> Maybe put a single logger call in the constructor instead of in `operator()`, or in the calling code before the `std::thread` call?

@geoffthemedio It was a purpose to catch close freezes in the logs. Also if it was logger issue it should break more often on disconnects.

**Comment by adrianbroher** [comment]
@geoffthemedio 

> Is that possible?

Well, yes.  But you would have to ditch all the macro magic.  

> Calls like TraceLogger(network) are a macro that expends, seemingly, into a for loop, not a getter for a reference to something

That for loop is probably a variation of the do-while idom to squeeze multiple C++ statements into a single macro safely and introduce a new scope:

https://pzemtsov.github.io/2014/05/05/do-macro.html

File: server/ServerNetworking.cpp [hunk 1]
```diff
@@ -165,6 +165,24 @@ PlayerConnection::PlayerConnection(boost::asio::io_context& io_context,
...
+namespace {
+    struct AsyncCloseClosure {
+        AsyncCloseClosure(boost::optional<boost::asio::ip::tcp::socket> &&socket, int id) :
+            m_socket(std::move(socket)),
+            m_id(id)
+        {}
+
+        void operator()() {
+            TraceLogger(network) << "Asynchronously closing socket for player id " << m_id;
+            m_socket->close();
```
Comment (geoffthemedio) [inline server/ServerNetworking.cpp]: since `m_socket` is an `optional` should probly check that it's not empty before using?

Comment (o01eg) [reply server/ServerNetworking.cpp]: No, because `m_socket` cannot be empty until destructor.

Comment (geoffthemedio) [reply server/ServerNetworking.cpp]: the `socket` parameter to the constructor is an `optional`, which could be empty...?

Comment (o01eg) [reply server/ServerNetworking.cpp]: No, `m_socket` isn't empty in `PlayerConnection` constructor and emptied only when move non-empty value to `AsyncCloseClosure`. It's uses optional because socket cannot be moved itself.

Comment (geoffthemedio) [reply server/ServerNetworking.cpp]: That might be OK if `AsyncCloseClosure` was defined locally to where it's used, but it looks like a general purpose bit of code that takes a parameter but doesn't verify its validity before using it...

Comment (geoffthemedio) [reply server/ServerNetworking.cpp]: could just do `if (m_socket) m_socket->close();` or somesuch... perhaps tweak the logger calls accordingly

Comment (o01eg) [reply server/ServerNetworking.cpp]: Logger calls accessed only `m_id` here.

File: server/ServerNetworking.cpp [hunk 2]
```diff
@@ -165,6 +165,25 @@ PlayerConnection::PlayerConnection(boost::asio::io_context& io_context,
...
+        AsyncCloseClosure(boost::optional<boost::asio::ip::tcp::socket> &&socket, int id) :
+            m_socket(std::move(socket)),
+            m_id(id)
+        {}
+
+        void operator()() {
+            TraceLogger(network) << "Asynchronously closing socket for player id " << m_id;
+            if (m_socket)
+                m_socket->close();
+            TraceLogger(network) << "Socket closed for player id " << m_id;
```
Comment (geoffthemedio) [inline server/ServerNetworking.cpp]: I just meant that if `m_socket` was empty, then the log saying that the socket was closed is misleading... since nothing was closed.

Comment (o01eg) [reply server/ServerNetworking.cpp]: Made `m_socket` test around log calls.
