### PR TITLE
Treat timeout read error as disconnection

### LINKED ISSUE #2232: Read timeout don't cause disconnection
### Environment
* **FreeOrion Version**: https://github.com/o01eg/freeorion/commit/dca64e05aca3c06097367bbca5b24a4aa64ffcf3 based on 321d6b8 v0.4.8
* **Operating System**: Ubuntu Linux 18.04 x64
* **Fetched as** 
  * Compiled from source

### Description
After long idling connection go to "ghost" state. It doesn't close when client disconnects and for long time doesn't cause any network error.
After some time connection gets `error #110 "Connection timed out"` but it doesn't cause disconnection.

freeoriond.log
```
07:09:41.926128 [trace] network : ServerNetworking.cpp:709 : ServerNetworking::AcceptConnection : connected to new player
07:09:41.926170 [trace] network : ServerNetworking.cpp:290 : Server received message from player id: -1 of type Join Game and size 385
07:09:41.926198 [debug] server : Message.cpp:903 : ExtractJoinGameMessageData() from  client type 21902
07:09:41.926302 [debug] server : ServerFSM.cpp:843 : MPLobby.JoinGame Try to login player o01eg with cookie: 00000000-0000-0000-0000-000000000000
07:09:41.926521 [debug] python : <string>:3 - Python current directory set to /usr/share/games/freeorion/default/python/auth
07:09:41.926602 [info] server : i18n.cpp:120 : Global locale: en_GB.UTF-8
07:09:41.927548 [debug] server : i18n.cpp:55 : Detected language: en
07:09:41.967474 [debug] python : <string>:3 - Python current directory set to /usr/share/games/freeorion/default/python/auth
07:09:41.967530 [debug] FSM : ServerFSM.cpp:900 : (ServerFSM) MPLobby.JoinGame player accepted: o01eg
07:09:41.967582 [debug] server : ServerFSM.cpp:344 : ServerFSM.EstablishPlayer Assign new player id 1
07:09:41.967593 [trace] network : ServerNetworking.cpp:157 : PlayerConnection(@ 0x558e1b65c2a0)::EstablishPlayer(1, o01eg, 1, v0.4.8 [build 2018-07-23.321d6b8
] CMake)
07:09:41.967887 [debug] server : ServerFSM.cpp:356 : ServerFSM.EstablishPlayer player o01eg get cookie: f117d52c-6649-4c81-9bd6-9f1532222865
...
07:13:45.200055 [debug] FSM : ServerFSM.cpp:977 : Get message from host or allowed player.
07:13:45.200186 [debug] FSM : ServerFSM.cpp:104 : PlayerSetupData:
07:13:45.200214 [debug] FSM : ServerFSM.cpp:119 :  ... 1 : o01eg, PLAYER, RANDOM
07:13:45.200232 [debug] FSM : ServerFSM.cpp:119 :  ... -1 : AI_1, AI_PLAYER, RANDOM
07:13:45.200246 [debug] FSM : ServerFSM.cpp:1361 : New save file: false. PSD changed: true. Important changes: true
08:40:50.943502 [trace] network : ServerNetworking.cpp:709 : ServerNetworking::AcceptConnection : connected to new player
08:40:50.943612 [trace] network : ServerNetworking.cpp:290 : Server received message from player id: -1 of type Join Game and size 385
08:40:50.943648 [debug] server : Message.cpp:903 : ExtractJoinGameMessageData() from  client type 21902
08:40:50.943746 [debug] server : ServerFSM.cpp:843 : MPLobby.JoinGame Try to login player o01eg with cookie: f117d52c-6649-4c81-9bd6-9f1532222865
08:40:50.944001 [debug] python : <string>:3 - Python current directory set to /usr/share/games/freeorion/default/python/auth
08:40:50.944179 [debug] python : <string>:3 - Python current directory set to /usr/share/games/freeorion/default/python/auth
08:40:50.944211 [debug] FSM : ServerFSM.cpp:900 : (ServerFSM) MPLobby.JoinGame player accepted: o01eg2
08:40:50.944276 [debug] server : ServerFSM.cpp:344 : ServerFSM.EstablishPlayer Assign new player id 2
08:40:50.944293 [trace] network : ServerNetworking.cpp:157 : PlayerConnection(@ 0x558e1ba36470)::EstablishPlayer(2, o01eg2, 1, v0.4.8 [build 2018-07-23.321d6b8] CMake)
08:40:50.944669 [debug] server : ServerFSM.cpp:356 : ServerFSM.EstablishPlayer player o01eg2 get cookie: 4f9ba00a-4115-431d-beb0-466676b006be
...
08:41:30.866653 [trace] network : ServerNetworking.cpp:719 : ServerNetworking::DisconnectImpl : disconnecting player 2 this = 0x558e1ba36470
08:41:30.866724 [debug] FSM : ServerFSM.cpp:701 : MPLobby::react(Disconnection) player id: 2
08:41:30.866738 [debug] FSM : ServerFSM.cpp:702 : Remaining player ids: 
08:41:30.866745 [debug] FSM : ServerFSM.cpp:706 :  ... 1 (o01eg)
08:41:30.866913 [trace] network : ServerNetworking.cpp:74 : PlayerConnection destruction player id 2 this = 0x558e1ba36470
08:57:21.352325 [error] network : ServerNetworking.cpp:342 : PlayerConnection::HandleMessageHeaderRead(): error #110 "Connection timed out"
09:13:31.314528 [trace] network : ServerNetworking.cpp:709 : ServerNetworking::AcceptConnection : connected to new player
09:13:31.314597 [trace] network : ServerNetworking.cpp:290 : Server received message from player id: -1 of type Join Game and size 385
09:13:31.314618 [debug] server : Message.cpp:903 : ExtractJoinGameMessageData() from  client type 21902
09:13:31.314687 [debug] server : ServerFSM.cpp:843 : MPLobby.JoinGame Try to login player o01eg with cookie: 4f9ba00a-4115-431d-beb0-466676b006be
09:13:31.314904 [debug] python : <string>:3 - Python current directory set to /usr/share/games/freeorion/default/python/auth
09:13:31.315022 [debug] python : <string>:3 - Python current directory set to /usr/share/games/freeorion/default/python/auth
09:13:31.315041 [debug] FSM : ServerFSM.cpp:900 : (ServerFSM) MPLobby.JoinGame player accepted: o01eg2
09:13:31.315070 [debug] server : ServerFSM.cpp:344 : ServerFSM.EstablishPlayer Assign new player id 2
09:13:31.315080 [trace] network : ServerNetworking.cpp:157 : PlayerConnection(@ 0x558e1b7e3100)::EstablishPlayer(2, o01eg2, 1, v0.4.8 [build 2018-07-23.321d6b8] CMake)
09:13:31.315384 [debug] server : ServerFSM.cpp:356 : ServerFSM.EstablishPlayer player o01eg2 get cookie: 51c5eec8-c2b9-43ba-a304-34d7c849da23
09:13:31.338293 [debug] server : Building.cpp:407 : BuildingTypeManager checksum: 6510164
09:13:31.338620 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 275303
09:13:31.338975 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 8509646
09:13:31.339203 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 3124966
09:13:31.339961 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 6908114
09:13:31.340729 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 6761842
09:13:31.340809 [debug] server : Field.cpp:226 : FieldTypeManager checksum: 7001032
09:13:31.362992 [debug] server : ShipDesign.cpp:766 : HullTypeManager checksum: 1001888
09:13:31.370467 [debug] server : ShipDesign.cpp:265 : PartTypeManager checksum: 2298239
09:13:31.371571 [debug] server : ShipDesign.cpp:1540 : PredefinedShipDesignManager checksum: 877965
09:13:31.479890 [debug] server : Species.cpp:629 : SpeciesManager checksum: 6639613
09:13:31.489983 [debug] server : Tech.cpp:715 : TechManager checksum: 7068800
09:13:31.490358 [error] network : ServerNetworking.cpp:393 : PlayerConnection::WriteMessage(): player id = 1 error #32 "Broken pipe this = 0x558e1b65c2a0
09:13:38.493178 [debug] server : Process.cpp:275 : Process::Impl::Kill calling kill(m_process_id, SIGKILL)
09:13:38.493769 [debug] server : Process.cpp:277 : Process::Impl::Kill calling waitpid(m_process_id, &status, 0)
09:13:42.436192 [debug] server : Process.cpp:279 : Process::Impl::Kill done
09:13:42.436380 [trace] network : ServerNetworking.cpp:404 : PlayerConnection::AsyncErrorHandler: player id = 1 handled error #32 error #125 this = 0x558e1b65c2a0
09:13:42.436420 [trace] network : ServerNetworking.cpp:719 : ServerNetworking::DisconnectImpl : disconnecting player 1 this = 0x558e1b65c2a0
09:13:42.436441 [debug] FSM : ServerFSM.cpp:701 : MPLobby::react(Disconnection) player id: 1
09:13:42.436454 [debug] FSM : ServerFSM.cpp:702 : Remaining player ids: 
09:13:42.436464 [debug] FSM : ServerFSM.cpp:706 :  ... 2 (o01eg2)
09:13:42.436729 [trace] network : ServerNetworking.cpp:74 : PlayerConnection destruction player id 1 this = 0x558e1b65c2a0
09:13:42.436746 [trace] network : ServerNetworking.cpp:89 : Player connection already down.
09:13:42.436784 [trace] network : ServerNetworking.cpp:719 : ServerNetworking::DisconnectImpl : disconnecting player 2 this = 0x558e1b7e3100
09:13:42.436797 [debug] FSM : ServerFSM.cpp:701 : MPLobby::react(Disconnection) player id: 2
09:13:42.436808 [debug] FSM : ServerFSM.cpp:702 : Remaining player ids: 
09:13:42.436823 [trace] network : ServerNetworking.cpp:74 : PlayerConnection destruction player id 2 this = 0x558e1b7e3100
```

### Expected Result
Broken connection will be disconnected and associate player leaves multiplayer lobby.

### Steps to reproduce

* Launch hostless server.
* Join client to the server.
* Wait 30 minutes.
* Close client.

### PR DESCRIPTION
**Pull request by o01eg**
Fixes #2232

### CODE REVIEW

File: network/ServerNetworking.cpp [hunk 1]
```diff
@@ -344,7 +344,8 @@ void PlayerConnection::HandleMessageHeaderRead(boost::system::error_code error,
             }
         } else {
             if (error == boost::asio::error::eof ||
-                error == boost::asio::error::connection_reset) {
+                error == boost::asio::error::connection_reset ||
+                error == boost::asio::error::timed_out) {
```
Comment (geoffthemedio) [inline network/ServerNetworking.cpp]: prefer `{` on newline

Comment (o01eg) [reply network/ServerNetworking.cpp]: Fixed.
