### PR TITLE
pedia planet detail - take current species name from species manager not planet

### LINKED ISSUE #5527: Planet pedia entry confused about local species
Bug Report
==========
* **FreeOrion Version**: master has main issue, arguably release 5.1.2 has lighter version

Description
-----------
In-game pedia entry about a planet lists habitability for all species in your empire that can colonize, to give you an overview of colonization options.

On released version, there is a small additional feature: to include the planet's existing species even if it can't colonize, so you can judge your re-colonization options there.

That feature is slightly broken on release as it shows the non-colonizing local species also on foreign planets, as long as you have the same planet-bound species in your empire anyway (if you don't have the species in your empire  somewhere already, then it wouldn't show it, per what seems to be the original spirit of the feature - only show your colonizing species, and non-colonizing species just as an exception for your own planets).

On master, this feature is much more broken - it always shows local inhabitants even on foreign planets. But gets severely confused about habitability of those if you don't have them already. Like shows "Adequate" instead of "Good" on some native's home planet or perhaps even 'uninhabitable'

If the feature should match on master what was there before in release version, then the foreign planets should not list their local species, ever (well, unless you have the species, but then it lists them from your own census, not from planet's original inhabitants).

But arguably this is a feature not a bug to show local species every time, in order to give you comparison not only in the context of colonization, but also in the context of annexation/invasion. But even so, it should show correct habitability for those, not get confused about it when you don't have the species in your empire already.

Bisect traces to 7636e022aa21dd666d2ac4f6cbf2077f6e9ff991 as the changelist that dropped "show only your empire's colonizing species unless it's their own planet" and replaced it with "always show local species" (possibly getting confused about what species we're talking about), though it seems to have broken habitability view in general, although subsequent changes fixed that a bit but not for the case I am describing here (when you don't own the species and look at foreign inhabited planet)

I can work on fixing this but would like to know the intended state - should the local species be always shown for the annexation/conquest context as well as originally intended colonization context, or should the original spirit be brought back to only show local species on your own planets, for colonization context

And is it worth fixing on release branch, either fixing foreign planets not to show the local species ever, regardless if you own them or not, or to bring the feature in to always show them (with correct habitability)

### PR DESCRIPTION
**Pull request by Blue-Award**
current species name is subject to change when simulating population under new management

fixes https://github.com/freeorion/freeorion/issues/5527

previously local planet species was not leaking out of the method that gathers species for consideration, but after https://github.com/freeorion/freeorion/commit/7636e022aa21dd666d2ac4f6cbf2077f6e9ff991 it is a feature to always include planet's current species

except during simulation of max pop under new management, the planet's species gets replaced by the various candidates and I gather string_view is losing the plot a bit

taking the string_view out of SpeciesManager is more stable, and other places are doing so (or making a local std::string copy)

### CODE REVIEW

**Comment by Blue-Award** [comment]
nb. I think the species manager is keying by species name? so perhaps instead

`auto reported_species_rng = species_manager.AllSpecies() | range_filter(should_report) | range_values | range_transform(to_name);`

that part could be

`auto reported_species_rng = species_manager.AllSpecies() | range_filter(should_report) | range_keys;`

but that's unrelated comment (and maybe one day it would be nice to key things less by strings and more by something faster)

**Comment by geoffthemedio** [comment]
I suppose in this case, the result of the range could be strings that copy the names rather than string views. Probably the time to run the effects calculation / simulation is much more than the time to allocate one string copy per species...  But using the names from the manager keys should also workI think.

**Comment by Blue-Award** [comment]
Yeah I think Species from SpeciesManager aren't suddenly dissapearing or being added? so original code would hold views to those and I gather that was fine, so I matched that for local species too, rather than changing return type to vector of strings (which would work too)

File: UI/EncyclopediaDetailPanel.cpp [hunk 1]
```diff
@@ -3134,8 +3134,14 @@ namespace {
         // -- planet's current species, if any
         {
             const std::string_view planet_current_species = planet.SpeciesName();
-            if (!planet_current_species.empty())
-                retval.push_back(planet_current_species);
+            if (!planet_current_species.empty()) {
+                const auto species = species_manager.GetSpecies(planet_current_species);
+                if (species) {
```
Comment (geoffthemedio) [inline UI/EncyclopediaDetailPanel.cpp]:
```suggestion
                if (const auto species = species_manager.GetSpecies(planet_current_species) {
```

File: UI/EncyclopediaDetailPanel.cpp [hunk 2]
```diff
@@ -3134,8 +3134,13 @@ namespace {
         // -- planet's current species, if any
         {
             const std::string_view planet_current_species = planet.SpeciesName();
-            if (!planet_current_species.empty())
-                retval.push_back(planet_current_species);
+            if (!planet_current_species.empty()) {
+                if (const auto species = species_manager.GetSpecies(planet_current_species) {
```
Comment (geoffthemedio) [inline UI/EncyclopediaDetailPanel.cpp]:
```suggestion
                if (const auto species = species_manager.GetSpecies(planet_current_species)) {
```

**Comment by Blue-Award** [comment]
Not sure, but can you easily squash those suggestions when merging in or should I rebase/fixup/force push?

**Comment by geoffthemedio** [comment]
squashing during merge is simple
