### PR TITLE
Protect empires of authenticated players

### LINKED ISSUE #2357: Disallow another player to play empire controlled by authorized player in load game.
### Environment
* **FreeOrion Version**: 0.4.8
* **Fetched as** 
  * Binary release
  * Weekly development build
  * Compiled from source

### Description
When authentication used to prevent other player to play as someone authenticated player it still possible to choose empire he played on loading saved game and get information or even make some turns in this game.

### Expected Result
When someone tries to load saved game with some authenticated players server should match current player name and previous player name otherwise return error.

### Steps to reproduce
* Start multiplayer game with authenticated players.
* Make a save.
* Load save without authenticated players and with different names.

### PR DESCRIPTION
**Pull request by o01eg**
Fix #2357 

Adds new flag to save game if player who controls empire was authenticated.
Forbids players with different player's name to choose this empire on loading.

### CODE REVIEW

File: server/ServerFSM.cpp [hunk 1]
```diff
@@ -1188,7 +1194,41 @@ sc::result MPLobby::react(const LobbyUpdate& msg) {
             // limit count of AI
             auto max_ai = GetOptionsDB().Get<int>("network.server.ai.max");
             if (ai_count <= max_ai || max_ai < 0) {
-                m_lobby_data->m_players    = incoming_lobby_data.m_players;
+                if (sender->HasAuthRole(Networking::ROLE_HOST)) {
+                    // don't check host.
+                    m_lobby_data->m_players    = incoming_lobby_data.m_players;
+                } else {
+                    // check player doesn't set protected empire to yourself
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: yourself -> themselves ?

not sure what this means...

File: server/ServerFSM.cpp [hunk 2]
```diff
@@ -1188,7 +1194,41 @@ sc::result MPLobby::react(const LobbyUpdate& msg) {
...
+                                incorrect_empire = true;
+                            }
+                        }
+                        break;
+                    }
+                    if (incorrect_empire) {
+                        has_important_changes = true;
+                        player_setup_data_changed = true;
+                    } else {
+                        // ToDo: non-host player could change only AI and himself
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: could -> should only be able to ?

File: server/ServerFSM.cpp [hunk 3]
```diff
@@ -1188,7 +1194,41 @@ sc::result MPLobby::react(const LobbyUpdate& msg) {
...
+                        m_lobby_data->m_players    = incoming_lobby_data.m_players;
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: if it's not lining up with something else, you don't need the extra spaces before `=`

File: Empire/Empire.cpp [hunk 4]
```diff
@@ -68,6 +69,9 @@ const std::string& Empire::Name() const
 const std::string& Empire::PlayerName() const
 { return m_player_name; }
 
+bool Empire::IsAuthenticated() const
```
Comment (geoffthemedio) [inline Empire/Empire.cpp:72]: does `m_authenticated` make sense as part of empire, and not of the server players list?

**Comment by geoffthemedio** [comment]
Some additional documentation in the code indicating what an empire being authenticated means would be helpful.

File: Empire/Empire.h [hunk 5]
```diff
@@ -327,6 +328,8 @@ class FO_COMMON_API Empire {
 
     void UpdateOwnedObjectCounters();
 
+    void SetAuthenticated(bool authenticated=true);
```
Comment (geoffthemedio) [inline Empire/Empire.h]: prefer spaces around `=`

File: Empire/Empire.h [hunk 6]
```diff
@@ -376,6 +379,7 @@ class FO_COMMON_API Empire {
     int                             m_id = ALL_EMPIRES;         ///< Empire's unique numeric id
     std::string                     m_name;                     ///< Empire's name
     std::string                     m_player_name;              ///< Empire's Player's name
+    bool                            m_authenticated;            ///< Empire's Player's authentication status
```
Comment (geoffthemedio) [inline Empire/Empire.h]: maybe this is the wrong thing to call this flag? It's not so much that the empire (or the player) is authenticated, but rather that the empire can only be played by the player who is authenticated with that name.

File: Empire/Empire.cpp (hunk 4 above)
Comment (o01eg) [reply Empire/Empire.cpp:72]: To use it in multiplayer lobby I need to have it in `SaveGameEmpireData` which populated from `Empire`. Also I can't use server player list because after #2379 it could be possible someone would be disconnected and its authentication status would be unreachable.

File: server/ServerFSM.cpp (hunk 1 above)
Comment (o01eg) [reply server/ServerFSM.cpp]: Fixed. It means player could set protected empire only if player have requested name.

File: server/ServerFSM.cpp (hunk 3 above)
Comment (o01eg) [reply server/ServerFSM.cpp]: Fixed.

File: server/ServerFSM.cpp (hunk 2 above)
Comment (o01eg) [reply server/ServerFSM.cpp]: Fixed.

File: Empire/Empire.h (hunk 6 above)
Comment (o01eg) [reply Empire/Empire.h]: Added more documentation here.

File: Empire/Empire.h (hunk 5 above)
Comment (o01eg) [reply Empire/Empire.h]: Fixed.

File: server/ServerApp.cpp [hunk 7]
```diff
@@ -1747,16 +1752,18 @@ void ServerApp::DropPlayerEmpireLink(int player_id)
 { m_player_empire_ids.erase(player_id); }
 
 int ServerApp::AddPlayerIntoGame(const PlayerConnectionPtr& player_connection) {
+    Empire* empire_ptr = nullptr;
```
Comment (geoffthemedio) [inline server/ServerApp.cpp]: prefer just `empire`. that it is a pointer is apparently clear enough from the use of `->` to access the member functions.

File: server/ServerFSM.cpp [hunk 8]
```diff
@@ -1188,7 +1194,42 @@ sc::result MPLobby::react(const LobbyUpdate& msg) {
             // limit count of AI
             auto max_ai = GetOptionsDB().Get<int>("network.server.ai.max");
             if (ai_count <= max_ai || max_ai < 0) {
-                m_lobby_data->m_players    = incoming_lobby_data.m_players;
+                if (sender->HasAuthRole(Networking::ROLE_HOST)) {
+                    // don't check host
```
Comment (geoffthemedio) [inline server/ServerFSM.cpp]: meaning the host can set any player to any empire, regardless of it nominally requiring an authenticated matching player name?

Comment (o01eg) [reply server/ServerFSM.cpp]: Yes, I suppose Host is a `root` of the server.

Comment (geoffthemedio) [reply server/ServerFSM.cpp]: please clarify this in the comment

File: server/ServerApp.cpp (hunk 7 above)
Comment (o01eg) [reply server/ServerApp.cpp]: Fixed.

File: server/ServerFSM.cpp (hunk 8 above)
Comment (o01eg) [reply server/ServerFSM.cpp]: Fixed.
